### ISSUE TITLE
what is the "assert num == len(path_list)" mean in average_model.py?

### ISSUE THREAD

**Issue by liyunlongaaa** [wenet-e2e/wespeaker#117]
https://github.com/wenet-e2e/wespeaker/blob/7a7c3b11c3888d0e5bb7e64d3a50efa17ac56397/wespeaker/bin/average_model.py#L54-L58
Hi, The purpose here is not to integrate all trained models, if I only train arg.nums models? What if the number of trained models is less than arg.nums, although this may not necessarily happen, but I think it should be considered in the code?

**Comment by JiJiJiang** [comment]
Emm...  We think "avg_num > trained_num" should never happen. If it was wrongly used, this assert error here could exactly raise a warnning !

**Comment by liyunlongaaa** [comment]
oh oh , I see !!
