### ISSUE TITLE
voxcelab/v2/local/prepare_data.sh  运行错误

### ISSUE THREAD

**Issue by zuowanbushiwo** [wenet-e2e/wespeaker#120]
你好 
      voxcelab/v2/local/prepare_data.sh line 83 -105行的  $(pwd) 是不是应该去掉，rawdata_dir 就是完整的路径了？对比cnceleb的prepare_data.sh 就没有这个参数？

**Comment by cdliang11** [comment]
你好，这个$(pwd)是为了得到绝对路径，cnceleb的prepare_data.sh中使用data=\`realpath $data\`，这两个效果是一样的

**Comment by zuowanbushiwo** [comment]
你好
    感谢回复 但是如果我的data 不在pwd 目录下就会出问题，比如我在run.sh 中 data 已经配置其他目录(绝对路径)就会有问题。cnceleb那种写法就不会有问题。

**Comment by cdliang11** [comment]
感谢建议，会进行修复
