### ISSUE TITLE
How to train ResNet293

### ISSUE THREAD

**Issue by EmreOzkose** [wenet-e2e/wespeaker#125]
Hi, how can I train ResNet293? In [config files](https://github.com/wenet-e2e/wespeaker/blob/c7043a08da898dee408271c3228d9652f120fe63/examples/voxceleb/v2/conf/resnet_lm.yaml#L47), maximum size is 152. Should I write a special config for Resnet293?

**Comment by JiJiJiang** [comment]
Just write ``ResNet293" in the config files and start training. I think everything should be fine.
