### ISSUE TITLE
8000 hz data 

### ISSUE THREAD

**Issue by EmreOzkose** [wenet-e2e/wespeaker#129]
Hi, 

Do you have any advice or experience for training 8000 hz data? Is it enough to change sampling rate [in config](https://github.com/wenet-e2e/wespeaker/blob/2d5c7afad7da65d8ba62391f6a1645460bb951f9/examples/voxceleb/v2/conf/resnet_lm.yaml#L30), or should I decrease [mel-size](https://github.com/wenet-e2e/wespeaker/blob/2d5c7afad7da65d8ba62391f6a1645460bb951f9/examples/voxceleb/v2/conf/resnet_lm.yaml#L35) from 80 to 40 ?

**Comment by JiJiJiang** [comment]
Hello,  set resample_rate as 8000 and the training is ready.
All data would be down-sampled into 8k HZ in an online manner while training, whatever 80-dim or 40-dim features are used.

**Comment by EmreOzkose** [comment]
Thank you @JiJiJiang. Should I decrease [num_frame](https://github.com/wenet-e2e/wespeaker/blob/2d5c7afad7da65d8ba62391f6a1645460bb951f9/examples/voxceleb/v2/conf/resnet_lm.yaml#L32) from 600 to 300 to do a meaningful training?

**Comment by EmreOzkose** [comment]
Or should I increase learning rate by 3 times, if I have 3 x #samples-in-voxceleb2-dev ? Do you have any experiments with other datasets ?

**Comment by JiJiJiang** [comment]
> 

No, you shouldn't. The training sample num per wave is calculated automatically according to **num_frms** and **resample_rate**.

**Comment by JiJiJiang** [comment]
> Or should I increase learning rate by 3 times, if I have 3 x #samples-in-voxceleb2-dev ? Do you have any experiments with other datasets ?

Joint training with other datasets should be fine. My suggestion is keeping the same lr and use a smaller epoch num (e.g., 150 => 120 or 100)
