### ISSUE TITLE
怎么没有 eval 过程？

### ISSUE THREAD

**Issue by zuowanbushiwo** [wenet-e2e/wespeaker#130]
你好
       发现训练过程没有验证集验证的过程？是这种任务不需要吗？能不能从训练集中每个speaker 取10%得数据，然后再自己生成一个trials， 这样每个epoch 后，计算这训练集 trials的eer？
谢谢！

**Comment by czy97** [comment]
> 你好 发现训练过程没有验证集验证的过程？是这种任务不需要吗？能不能从训练集中每个speaker 取10%得数据，然后再自己生成一个trials， 这样每个epoch 后，计算这训练集 trials的eer？ 谢谢！

是可以的，我们最近也在考虑最终这件事要怎么做，谢谢意见

**Comment by zuowanbushiwo** [comment]
好的，期待中！

**Comment by yuGAN6** [comment]
我感觉是因为声纹trials多，eval时间比较长。如果加到训练过程串行进行，对训练时间影响较大。如果在训练完再测试trials，可以开多进程，出结果会快点。
