### ISSUE TITLE
CRC error on VoxCeleb-ResNet34 pretrained checkpoint

### ISSUE THREAD

**Issue by hsiaohan0827** [wenet-e2e/wespeaker#145]
Hi, thanks for sharing the pretrained checkpoints!
I found that a CRC error occurred when I unzip the checkpoint of VoxCeleb-ResNet34 (from https://wespeaker-1256283475.cos.ap-shanghai.myqcloud.com/models/voxceleb/voxceleb_resnet34_LM.zip) and the corrupted file cannot be loaded in torch.
Since the downloaded checkpoint of CNCeleb-ResNet3 works just fine, I'm wondering if there's something wrong with the VoxCeleb-ResNet34 one. Thanks.

**Comment by cdliang11** [comment]
Hello, I cannot reproduce this error. Maybe you can try downloading the file again.

**Comment by hsiaohan0827** [comment]
After I redownload the file, the checkpoint works well. Thanks for your help :)
