### ISSUE TITLE
Setting dither = 0 during inference

### ISSUE THREAD

**Issue by EmreOzkose** [wenet-e2e/wespeaker#146]
Hi,

During training, features are extracted with [dither=1.0](https://github.com/wenet-e2e/wespeaker/blob/ca9bda0319071a4d614a7697e9ddc55486561042/examples/voxceleb/v2/conf/resnet.yaml#L32). However, during inference, features are forced to be extracted with [dither=0.0](https://github.com/wenet-e2e/wespeaker/blob/ca9bda0319071a4d614a7697e9ddc55486561042/wespeaker/bin/extract.py#L52). Is it a bug?

**Comment by cdliang11** [comment]
Hi, `dither` is the coefficient of the added random noise, which is equivalent to increasing the dither and is used during training. During inference, `dither=0.0`.
