### ISSUE TITLE
关于使用python预训练模型

### ISSUE THREAD

**Issue by phchtl** [wenet-e2e/wespeaker#150]
我通过python binding的方式使用预训练模型，进行说话人识别推理，但是推理的过程中没有使用gpu，速度很慢，请问怎么样才可以打开gpu加速推理过程，谢谢你！

**Comment by JiJiJiang** [comment]
@cdliang11 关注一下哈

**Comment by cdliang11** [comment]
> 我通过python binding的方式使用预训练模型，进行说话人识别推理，但是推理的过程中没有使用gpu，速度很慢，请问怎么样才可以打开gpu加速推理过程，谢谢你！

 目前python binding不支持GPU，可以参考https://github.com/wenet-e2e/wespeaker/blob/master/runtime/binding/python/py/speaker.py这个代码进行部分修改

**Comment by phchtl** [comment]
> > 我通过python binding的方式使用预训练模型，进行说话人识别推理，但是推理的过程中没有使用gpu，速度很慢，请问怎么样才可以打开gpu加速推理过程，谢谢你！
> 
> 目前python binding不支持GPU，可以参考[https://github.com/wenet-e2e/wespeaker/blob/master/runtime/binding/python/py/speaker.py这个代码进行部分修改](https://github.com/wenet-e2e/wespeaker/blob/master/runtime/binding/python/py/speaker.py%E8%BF%99%E4%B8%AA%E4%BB%A3%E7%A0%81%E8%BF%9B%E8%A1%8C%E9%83%A8%E5%88%86%E4%BF%AE%E6%94%B9)

目前我已解决，只要安装onnxruntime-gpu，卸载原来的onnxruntime就可以，然后在ort.InferenceSession函数中指定设备就行了
