### ISSUE TITLE
使用进行多语种识别出错

### ISSUE THREAD

**Issue by TongtongSong** [wenet-e2e/wespeaker#151]
在使用四语种分类时正常，用同样的代码进行多语种分类时出错，模型不收敛，这有可能是什么原因导致的呢

**Comment by JiJiJiang** [comment]
1. 首先考虑一下数据是否准备正确，有无标注出错的情况；
2. 看看不收敛的位置是在第几个epoch，如果是在加margin之后才导致的，可以试试只用softmax训练

**Comment by TongtongSong** [comment]
> 1. 首先考虑一下数据是否准备正确，有无标注出错的情况；
> 2. 看看不收敛的位置是在第几个epoch，如果是在加margin之后才导致的，可以试试只用softmax训练

数据目前查看没有问题。我试试第二个策略。感谢您的解答。
