### ISSUE TITLE
infer_onnx.py的waveform * (1<<15)的操作

### ISSUE THREAD

**Issue by LevanaRu** [wenet-e2e/wespeaker#154]
infer_onnx.py的waveform * (1<<15)的操作是为什么呢？

**Comment by xx205** [comment]
kaldi 用于提取 FBANK 的 wav 数据范围是 -32768~32767。waveform * (1<<15) 用于将数据范围从 [-1,1) 还原到 [-32768,32767)。

On Apr 29, 2023, at 23:30, LevanaRu ***@***.***> wrote:

﻿

infer_onnx.py的waveform * (1<<15)的操作是为什么呢？
