### ISSUE TITLE
train with voxceleb1&2 dev set

### ISSUE THREAD

**Issue by ductuantruong** [wenet-e2e/wespeaker#162]
Hi, 

Thank you for sharing your amazing work. I am trying to use your work in my research. However, the current Voxceleb recipe just allows training on Voxceleb 2 dev set and testing on Voxceleb 1 eval set. Could I ask how to perform model training on the Voxceleb1&2 dev set under the shard input format?

Thank you for your support!

**Comment by cdliang11** [comment]
Hi,
Just make some modifications to local/prepare_data.sh so that the wav.scp contains the data of vox2&1 dev set.

https://github.com/wenet-e2e/wespeaker/blob/d13d00e3dd890f95359879929d287c7e3af78dac/examples/voxceleb/v2/local/prepare_data.sh#L106-L107

**Comment by ductuantruong** [comment]
Hi, 

Thank you for your fast response. I change line 106 in [https://github.com/wenet-e2e/wespeaker/blob/d13d00e3dd890f95359879929d287c7e3af78dac/examples/voxceleb/v2/local/prepare_data.sh#L106-L107](url) to 
`find ${rawdata_dir}/voxceleb2_wav ${rawdata_dir}/voxceleb1/dev -name "*.wav" | awk -F"/" '{print $(NF-2)"/"$(NF-1)"/"$NF,$0}' | sort >${data}/vox2_dev/wav.scp`.

Then, I just need to re-run stage 4 of _/local/prepare_data.sh_ and stage 2 of _run.sh_ to convert the new train set to shard. Is it anything else I need to do before performing training on vov1&2 dev?

**Comment by cdliang11** [comment]
Hi,
I don't think there is anything else to do. But you need to ensure that vox1 dev set is not included in the test set.

**Comment by ductuantruong** [comment]
Thanks for the heads up. Since I included _${rawdata_dir}/voxceleb1/dev_, I believe there is no overlap between the train & test set. Once again, thank you very much for your help. It saves me a lot of time. I am closing the issue now.
