### ISSUE TITLE
能否上传一下train log

### ISSUE THREAD

**Issue by fxyouruo** [wenet-e2e/wespeaker#165]
尝试使用ResNet34-TSTP-emb256-fbank80-num_frms200-aug0.6-spTrue-saFalse-ArcMargin-SGD-epoch150的示例，发现训练到120个epoch，ACC只有77.16，loss=1.22；想知道这个进展是正常的嘛？
训练数据：vox2_dev
训练耗时：1小时/epoch，V100，4 GPUs

**Comment by cdliang11** [comment]
这个应该loss acc 应该是正常，可以跑一下测试看下eer

**Comment by fxyouruo** [comment]
> 这个loss acc 应该是正常，可以跑一下测试看下eer

嗯嗯，好的，非常非常感谢！！！再咨询一下哈，按照你们的训练经验，训练最大epoch数是否需要增加呢？比如增加到200，因为从性能曲线上来看，并没有收敛。

**Comment by cdliang11** [comment]
> > 这个loss acc 应该是正常，可以跑一下测试看下eer
> 
> 嗯嗯，好的，非常非常感谢！！！再咨询一下哈，按照你们的训练经验，训练最大epoch数是否需要增加呢？比如增加到200，因为从性能曲线上来看，并没有收敛。

我的个人经验：ep165 和 ep150 性能相差不大。你可以试试哈
