### ISSUE TITLE
关于wespeaker提取说话人嵌入

### ISSUE THREAD

**Issue by yyz845935161** [wenet-e2e/wespeaker#170]
请问该工具是否可以使用mel谱图，或者语谱图作为输入进行speake embedding，因为好多语音合成任务中都是使用mel谱图作为模型的输入和输出

**Comment by wsstriving** [comment]
需要重新训练模型，可以用feat 模式读取你事先提好的mel 特征，或者直接把相应的提取function 实现在processor 里，参考里边的compute_fbank.
