### ISSUE TITLE
参数保存问题

### ISSUE THREAD

**Issue by speechless-z** [wenet-e2e/wespeaker#172]
在训练时，projection_args中可以参数类型，然后这部分的参数是不是并没有保存到最终模型中呢？那这部分参数我在训练完成后想调用是不是不能用了呀？

**Comment by cdliang11** [comment]
保存了, 训练过程中保存的pt模型是带有projection_args `$exp_dir/models/*.pt`，部署的onnx模型没有带

**Comment by speechless-z** [comment]
好的好的，我明白了，是我没打印全，感谢
