### ISSUE TITLE
Issue with generating nan values ​​in sphereface2 loss function

### ISSUE THREAD

**Issue by greatnoble** [wenet-e2e/wespeaker#178]
I am a speech processing researcher who studies speaker recognition using the wespeaker tool.

A new loss function, the sphereface2 module, was introduced in the wespeaker tool, so I tested it using voxceleb DB.

As shown in the log below, it was observed that a Nan value was generated in the loss value.

Experimenting with the same settings, in some cases no nan values ​​occur and training ends.

However, when experimenting with the same settings, nan values ​​are generated.

In the v2/conf/resnet.yaml file, the model name was "ResNet152", and the project_type was set to "sphereface2" to experiment.

Can you comment on what causes the nan values?

[train log]
[ INFO : 2023-07-06 07:55:30,898 ] - |         3|       200|   0.52112|         0|    5.2225|    9.7266|
[ INFO : 2023-07-06 07:55:30,898 ] - |         3|       200|   0.52112|         0|    3.8506|    18.965|
[ INFO : 2023-07-06 07:55:30,898 ] - |         3|       200|   0.52112|         0|    3.9819|    17.094|
[ INFO : 2023-07-06 07:55:30,898 ] - |         3|       200|   0.52112|         0|    3.8734|    18.602|
[ INFO : 2023-07-06 07:55:30,898 ] - |         3|       200|   0.52112|         0|    4.0083|     16.66|
[ INFO : 2023-07-06 07:55:30,899 ] - |         3|       200|   0.52112|         0|    3.8383|     18.98|
[ INFO : 2023-07-06 07:55:30,903 ] - |         3|       200|   0.52112|         0|    3.9939|    17.066|
[ INFO : 2023-07-06 07:56:53,859 ] - |         3|       300|   0.54052|         0|       nan|    17.698|
[ INFO : 2023-07-06 07:56:53,860 ] - |         3|       300|   0.54052|         0|       nan|      16.5|
[ INFO : 2023-07-06 07:56:53,860 ] - |         3|       300|   0.54052|         0|       nan|    10.859|
[ INFO : 2023-07-06 07:56:53,860 ] - |         3|       300|   0.54052|         0|       nan|    18.258|
[ INFO : 2023-07-06 07:56:53,860 ] - |         3|       300|   0.54052|         0|       nan|    16.273|
[ INFO : 2023-07-06 07:56:53,861 ] - |         3|       300|   0.54052|         0|       nan|    18.099|
[ INFO : 2023-07-06 07:56:53,861 ] - |         3|       300|   0.54052|         0|       nan|    17.799|
[ INFO : 2023-07-06 07:56:53,864 ] - |         3|       300|   0.54052|         0|       nan|    16.539|
[ INFO : 2023-07-06 07:58:16,756 ] - |         3|       400|   0.55973|         0|       nan|    8.1445|
[ INFO : 2023-07-06 07:58:16,756 ] - |         3|       400|   0.55973|         0|       nan|    12.375|
[ INFO : 2023-07-06 07:58:16,756 ] - |         3|       400|   0.55973|         0|       nan|    13.574|
[ INFO : 2023-07-06 07:58:16,756 ] - |         3|       400|   0.55973|         0|       nan|     13.35|
[ INFO : 2023-07-06 07:58:16,756 ] - |         3|       400|   0.55973|         0|       nan|    12.205|
[ INFO : 2023-07-06 07:58:16,756 ] - |         3|       400|   0.55973|         0|       nan|    13.693|
[ INFO : 2023-07-06 07:58:16,757 ] - |         3|       400|   0.55973|         0|       nan|    13.273|
[ INFO : 2023-07-06 07:58:16,760 ] - |         3|       400|   0.55973|         0|       nan|    12.404|
[ INFO : 2023-07-06 07:59:40,291 ] - |         3|       500|   0.57875|         0|       nan|    10.619|
[ INFO : 2023-07-06 07:59:40,292 ] - |         3|       500|   0.57875|         0|       nan|     10.68|
[ INFO : 2023-07-06 07:59:40,292 ] - |         3|       500|   0.57875|         0|       nan|       9.9|
[ INFO : 2023-07-06 07:59:40,292 ] - |         3|       500|   0.57875|         0|       nan|    6.5156|
[ INFO : 2023-07-06 07:59:40,292 ] - |         3|       500|   0.57875|         0|       nan|    10.859|
[ INFO : 2023-07-06 07:59:40,292 ] - |         3|       500|   0.57875|         0|       nan|    9.7641|
[ INFO : 2023-07-06 07:59:40,293 ] - |         3|       500|   0.57875|         0|       nan|    10.955|
[ INFO : 2023-07-06 07:59:40,296 ] - |         3|       500|   0.57875|         0|       nan|    9.9234|
[ INFO : 2023-07-06 08:01:06,822 ] - |         3|       600|   0.59758|         0|       nan|     8.849|
[ INFO : 2023-07-06 08:01:06,822 ] - |         3|       600|   0.59758|         0|       nan|    5.4297|
[ INFO : 2023-07-06 08:01:06,823 ] - |         3|       600|   0.59758|         0|       nan|    9.1289|
[ INFO : 2023-07-06 08:01:06,823 ] - |         3|       600|   0.59758|         0|       nan|    8.8997|
[ INFO : 2023-07-06 08:01:06,823 ] - |         3|       600|   0.59758|         0|       nan|      8.25|
[ INFO : 2023-07-06 08:01:06,823 ] - |         3|       600|   0.59758|         0|       nan|    8.1367|
[ INFO : 2023-07-06 08:01:06,823 ] - |         3|       600|   0.59758|         0|       nan|    9.0495|
[ INFO : 2023-07-06 08:01:06,827 ] - |         3|       600|   0.59758|         0|       nan|    8.2695|
[ INFO : 2023-07-06 08:02:29,752 ] - |         3|       700|   0.61623|         0|       nan|    7.0714|
[ INFO : 2023-07-06 08:02:29,752 ] - |         3|       700|   0.61623|         0|       nan|     4.654|
[ INFO : 2023-07-06 08:02:29,752 ] - |         3|       700|   0.61623|         0|       nan|    7.6283|
[ INFO : 2023-07-06 08:02:29,752 ] - |         3|       700|   0.61623|         0|       nan|    7.7567|
[ INFO : 2023-07-06 08:02:29,752 ] - |         3|       700|   0.61623|         0|       nan|    7.5848|
[ INFO : 2023-07-06 08:02:29,753 ] - |         3|       700|   0.61623|         0|       nan|    7.8248|
[ INFO : 2023-07-06 08:02:29,753 ] - |         3|       700|   0.61623|         0|       nan|    6.9743|
[ INFO : 2023-07-06 08:02:29,756 ] - |         3|       700|   0.61623|         0|       nan|    7.0882|
[ INFO : 2023-07-06 08:03:52,705 ] - |         3|       800|   0.63469|         0|       nan|    6.6367|
[ INFO : 2023-07-06 08:03:52,706 ] - |         3|       800|   0.63469|         0|       nan|    6.1875|
[ INFO : 2023-07-06 08:03:52,706 ] - |         3|       800|   0.63469|         0|       nan|    4.0723|
[ INFO : 2023-07-06 08:03:52,706 ] - |         3|       800|   0.63469|         0|       nan|    6.8467|
[ INFO : 2023-07-06 08:03:52,706 ] - |         3|       800|   0.63469|         0|       nan|    6.7871|
[ INFO : 2023-07-06 08:03:52,706 ] - |         3|       800|   0.63469|         0|       nan|    6.6748|
[ INFO : 2023-07-06 08:03:52,706 ] - |         3|       800|   0.63469|         0|       nan|    6.1025|
[ INFO : 2023-07-06 08:03:52,710 ] - |         3|       800|   0.63469|         0|       nan|    6.2021|
[ INFO : 2023-07-06 08:05:18,838 ] - |         3|       900|   0.65296|         0|       nan|       5.5|
[ INFO : 2023-07-06 08:05:18,839 ] - |         3|       900|   0.65296|         0|       nan|    3.6198|
[ INFO : 2023-07-06 08:05:18,839 ] - |         3|       900|   0.65296|         0|       nan|     6.033|
[ INFO : 2023-07-06 08:05:18,839 ] - |         3|       900|   0.65296|         0|       nan|    6.0859|
[ INFO : 2023-07-06 08:05:18,839 ] - |         3|       900|   0.65296|         0|       nan|    5.8993|
[ INFO : 2023-07-06 08:05:18,839 ] - |         3|       900|   0.65296|         0|       nan|    5.4245|
[ INFO : 2023-07-06 08:05:18,839 ] - |         3|       900|   0.65296|         0|       nan|    5.9332|
[ INFO : 2023-07-06 08:05:18,842 ] - |         3|       900|   0.65296|         0|       nan|     5.513|
[ INFO : 2023-07-06 08:06:41,560 ] - |         3|      1000|   0.67105|         0|       nan|    5.3094|
[ INFO : 2023-07-06 08:06:41,561 ] - |         3|      1000|   0.67105|         0|       nan|    5.4297|
[ INFO : 2023-07-06 08:06:41,561 ] - |         3|      1000|   0.67105|         0|       nan|    5.4773|
[ INFO : 2023-07-06 08:06:41,561 ] - |         3|      1000|   0.67105|         0|       nan|      4.95|
[ INFO : 2023-07-06 08:06:41,561 ] - |         3|      1000|   0.67105|         0|       nan|    5.3398|
[ INFO : 2023-07-06 08:06:41,561 ] - |         3|      1000|   0.67105|         0|       nan|     4.882|
[ INFO : 2023-07-06 08:06:41,562 ] - |         3|      1000|   0.67105|         0|       nan|    3.2578|
[ INFO : 2023-07-06 08:06:41,564 ] - |         3|      1000|   0.67105|         0|       nan|    4.9617|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1082|   0.68575|         0|       nan|    5.0622|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1088|   0.68682|         0|       nan|    4.8799|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1080|   0.68539|         0|       nan|    4.5833|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1088|   0.68682|         0|       nan|    4.9079|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1080|   0.68539|         0|       nan|    3.0165|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1080|   0.68539|         0|       nan|    4.5942|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1080|   0.68539|         0|       nan|    4.5204|
[ INFO : 2023-07-06 08:07:55,262 ] - |         3|      1088|   0.68682|         0|       nan|    4.9905|
[ INFO : 2023-07-06 08:09:32,093 ] - |         4|       100|   0.70475|         0|       nan|         0|
[ INFO : 2023-07-06 08:09:32,093 ] - |         4|       100|   0.70475|         0|       nan|         0|
[ INFO : 2023-07-06 08:09:32,093 ] - |         4|       100|   0.70475|         0|       nan|         0|
[ INFO : 2023-07-06 08:09:32,093 ] - |         4|       100|   0.70475|         0|       nan|         0|
[ INFO : 2023-07-06 08:09:32,093 ] - |         4|       100|   0.70475|         0|       nan| 0.0078125|
[ INFO : 2023-07-06 08:09:32,094 ] - |         4|       100|   0.70475|         0|       nan|         0|
[ INFO : 2023-07-06 08:09:32,093 ] - |         4|       100|   0.70475|         0|       nan|         0|
[ INFO : 2023-07-06 08:09:32,096 ] - |         4|       100|   0.70475|         0|       nan|         0|
[ INFO : 2023-07-06 08:11:00,766 ] - |         4|       200|   0.72232|         0|       nan|         0|
[ INFO : 2023-07-06 08:11:00,766 ] - |         4|       200|   0.72232|         0|       nan|         0|

**Comment by Hunterhuan** [comment]
> 

Sorry, I can't reproduce your problem.

I try to run the ResNet152, sphereface2 with batchsize 64 on 8 x V100. Now, the epoch has reached 19 but there is no nan value in the loss.

Could you give more detail about the training?

**Comment by Hunterhuan** [comment]
> I am a speech processing researcher who studies speaker recognition using the wespeaker tool.
> 
> A new loss function, the sphereface2 module, was introduced in the wespeaker tool, so I tested it using voxceleb DB.
> 
> As shown in the log below, it was observed that a Nan value was generated in the loss value.
> 
> Experimenting with the same settings, in some cases no nan values ​​occur and training ends.
> 
> However, when experimenting with the same settings, nan values ​​are generated.
> 
> In the v2/conf/resnet.yaml file, the model name was "ResNet152", and the project_type was set to "sphereface2" to experiment.
> 
> Can you comment on what causes the nan values?
> 
> [train log] [ INFO : 2023-07-06 07:55:30,898 ] - | 3| 200| 0.52112| 0| 5.2225| 9.7266| [ INFO : 2023-07-06 07:55:30,898 ] - | 3| 200| 0.52112| 0| 3.8506| 18.965| [ INFO : 2023-07-06 07:55:30,898 ] - | 3| 200| 0.52112| 0| 3.9819| 17.094| [ INFO : 2023-07-06 07:55:30,898 ] - | 3| 200| 0.52112| 0| 3.8734| 18.602| [ INFO : 2023-07-06 07:55:30,898 ] - | 3| 200| 0.52112| 0| 4.0083| 16.66| [ INFO : 2023-07-06 07:55:30,899 ] - | 3| 200| 0.52112| 0| 3.8383| 18.98| [ INFO : 2023-07-06 07:55:30,903 ] - | 3| 200| 0.52112| 0| 3.9939| 17.066| [ INFO : 2023-07-06 07:56:53,859 ] - | 3| 300| 0.54052| 0| nan| 17.698| [ INFO : 2023-07-06 07:56:53,860 ] - | 3| 300| 0.54052| 0| nan| 16.5| [ INFO : 2023-07-06 07:56:53,860 ] - | 3| 300| 0.54052| 0| nan| 10.859| [ INFO : 2023-07-06 07:56:53,860 ] - | 3| 300| 0.54052| 0| nan| 18.258| [ INFO : 2023-07-06 07:56:53,860 ] - | 3| 300| 0.54052| 0| nan| 16.273| [ INFO : 2023-07-06 07:56:53,861 ] - | 3| 300| 0.54052| 0| nan| 18.099| [ INFO : 2023-07-06 07:56:53,861 ] - | 3| 300| 0.54052| 0| nan| 17.799| [ INFO : 2023-07-06 07:56:53,864 ] - | 3| 300| 0.54052| 0| nan| 16.539| [ INFO : 2023-07-06 07:58:16,756 ] - | 3| 400| 0.55973| 0| nan| 8.1445| [ INFO : 2023-07-06 07:58:16,756 ] - | 3| 400| 0.55973| 0| nan| 12.375| [ INFO : 2023-07-06 07:58:16,756 ] - | 3| 400| 0.55973| 0| nan| 13.574| [ INFO : 2023-07-06 07:58:16,756 ] - | 3| 400| 0.55973| 0| nan| 13.35| [ INFO : 2023-07-06 07:58:16,756 ] - | 3| 400| 0.55973| 0| nan| 12.205| [ INFO : 2023-07-06 07:58:16,756 ] - | 3| 400| 0.55973| 0| nan| 13.693| [ INFO : 2023-07-06 07:58:16,757 ] - | 3| 400| 0.55973| 0| nan| 13.273| [ INFO : 2023-07-06 07:58:16,760 ] - | 3| 400| 0.55973| 0| nan| 12.404| [ INFO : 2023-07-06 07:59:40,291 ] - | 3| 500| 0.57875| 0| nan| 10.619| [ INFO : 2023-07-06 07:59:40,292 ] - | 3| 500| 0.57875| 0| nan| 10.68| [ INFO : 2023-07-06 07:59:40,292 ] - | 3| 500| 0.57875| 0| nan| 9.9| [ INFO : 2023-07-06 07:59:40,292 ] - | 3| 500| 0.57875| 0| nan| 6.5156| [ INFO : 2023-07-06 07:59:40,292 ] - | 3| 500| 0.57875| 0| nan| 10.859| [ INFO : 2023-07-06 07:59:40,292 ] - | 3| 500| 0.57875| 0| nan| 9.7641| [ INFO : 2023-07-06 07:59:40,293 ] - | 3| 500| 0.57875| 0| nan| 10.955| [ INFO : 2023-07-06 07:59:40,296 ] - | 3| 500| 0.57875| 0| nan| 9.9234| [ INFO : 2023-07-06 08:01:06,822 ] - | 3| 600| 0.59758| 0| nan| 8.849| [ INFO : 2023-07-06 08:01:06,822 ] - | 3| 600| 0.59758| 0| nan| 5.4297| [ INFO : 2023-07-06 08:01:06,823 ] - | 3| 600| 0.59758| 0| nan| 9.1289| [ INFO : 2023-07-06 08:01:06,823 ] - | 3| 600| 0.59758| 0| nan| 8.8997| [ INFO : 2023-07-06 08:01:06,823 ] - | 3| 600| 0.59758| 0| nan| 8.25| [ INFO : 2023-07-06 08:01:06,823 ] - | 3| 600| 0.59758| 0| nan| 8.1367| [ INFO : 2023-07-06 08:01:06,823 ] - | 3| 600| 0.59758| 0| nan| 9.0495| [ INFO : 2023-07-06 08:01:06,827 ] - | 3| 600| 0.59758| 0| nan| 8.2695| [ INFO : 2023-07-06 08:02:29,752 ] - | 3| 700| 0.61623| 0| nan| 7.0714| [ INFO : 2023-07-06 08:02:29,752 ] - | 3| 700| 0.61623| 0| nan| 4.654| [ INFO : 2023-07-06 08:02:29,752 ] - | 3| 700| 0.61623| 0| nan| 7.6283| [ INFO : 2023-07-06 08:02:29,752 ] - | 3| 700| 0.61623| 0| nan| 7.7567| [ INFO : 2023-07-06 08:02:29,752 ] - | 3| 700| 0.61623| 0| nan| 7.5848| [ INFO : 2023-07-06 08:02:29,753 ] - | 3| 700| 0.61623| 0| nan| 7.8248| [ INFO : 2023-07-06 08:02:29,753 ] - | 3| 700| 0.61623| 0| nan| 6.9743| [ INFO : 2023-07-06 08:02:29,756 ] - | 3| 700| 0.61623| 0| nan| 7.0882| [ INFO : 2023-07-06 08:03:52,705 ] - | 3| 800| 0.63469| 0| nan| 6.6367| [ INFO : 2023-07-06 08:03:52,706 ] - | 3| 800| 0.63469| 0| nan| 6.1875| [ INFO : 2023-07-06 08:03:52,706 ] - | 3| 800| 0.63469| 0| nan| 4.0723| [ INFO : 2023-07-06 08:03:52,706 ] - | 3| 800| 0.63469| 0| nan| 6.8467| [ INFO : 2023-07-06 08:03:52,706 ] - | 3| 800| 0.63469| 0| nan| 6.7871| [ INFO : 2023-07-06 08:03:52,706 ] - | 3| 800| 0.63469| 0| nan| 6.6748| [ INFO : 2023-07-06 08:03:52,706 ] - | 3| 800| 0.63469| 0| nan| 6.1025| [ INFO : 2023-07-06 08:03:52,710 ] - | 3| 800| 0.63469| 0| nan| 6.2021| [ INFO : 2023-07-06 08:05:18,838 ] - | 3| 900| 0.65296| 0| nan| 5.5| [ INFO : 2023-07-06 08:05:18,839 ] - | 3| 900| 0.65296| 0| nan| 3.6198| [ INFO : 2023-07-06 08:05:18,839 ] - | 3| 900| 0.65296| 0| nan| 6.033| [ INFO : 2023-07-06 08:05:18,839 ] - | 3| 900| 0.65296| 0| nan| 6.0859| [ INFO : 2023-07-06 08:05:18,839 ] - | 3| 900| 0.65296| 0| nan| 5.8993| [ INFO : 2023-07-06 08:05:18,839 ] - | 3| 900| 0.65296| 0| nan| 5.4245| [ INFO : 2023-07-06 08:05:18,839 ] - | 3| 900| 0.65296| 0| nan| 5.9332| [ INFO : 2023-07-06 08:05:18,842 ] - | 3| 900| 0.65296| 0| nan| 5.513| [ INFO : 2023-07-06 08:06:41,560 ] - | 3| 1000| 0.67105| 0| nan| 5.3094| [ INFO : 2023-07-06 08:06:41,561 ] - | 3| 1000| 0.67105| 0| nan| 5.4297| [ INFO : 2023-07-06 08:06:41,561 ] - | 3| 1000| 0.67105| 0| nan| 5.4773| [ INFO : 2023-07-06 08:06:41,561 ] - | 3| 1000| 0.67105| 0| nan| 4.95| [ INFO : 2023-07-06 08:06:41,561 ] - | 3| 1000| 0.67105| 0| nan| 5.3398| [ INFO : 2023-07-06 08:06:41,561 ] - | 3| 1000| 0.67105| 0| nan| 4.882| [ INFO : 2023-07-06 08:06:41,562 ] - | 3| 1000| 0.67105| 0| nan| 3.2578| [ INFO : 2023-07-06 08:06:41,564 ] - | 3| 1000| 0.67105| 0| nan| 4.9617| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1082| 0.68575| 0| nan| 5.0622| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1088| 0.68682| 0| nan| 4.8799| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1080| 0.68539| 0| nan| 4.5833| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1088| 0.68682| 0| nan| 4.9079| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1080| 0.68539| 0| nan| 3.0165| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1080| 0.68539| 0| nan| 4.5942| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1080| 0.68539| 0| nan| 4.5204| [ INFO : 2023-07-06 08:07:55,262 ] - | 3| 1088| 0.68682| 0| nan| 4.9905| [ INFO : 2023-07-06 08:09:32,093 ] - | 4| 100| 0.70475| 0| nan| 0| [ INFO : 2023-07-06 08:09:32,093 ] - | 4| 100| 0.70475| 0| nan| 0| [ INFO : 2023-07-06 08:09:32,093 ] - | 4| 100| 0.70475| 0| nan| 0| [ INFO : 2023-07-06 08:09:32,093 ] - | 4| 100| 0.70475| 0| nan| 0| [ INFO : 2023-07-06 08:09:32,093 ] - | 4| 100| 0.70475| 0| nan| 0.0078125| [ INFO : 2023-07-06 08:09:32,094 ] - | 4| 100| 0.70475| 0| nan| 0| [ INFO : 2023-07-06 08:09:32,093 ] - | 4| 100| 0.70475| 0| nan| 0| [ INFO : 2023-07-06 08:09:32,096 ] - | 4| 100| 0.70475| 0| nan| 0| [ INFO : 2023-07-06 08:11:00,766 ] - | 4| 200| 0.72232| 0| nan| 0| [ INFO : 2023-07-06 08:11:00,766 ] - | 4| 200| 0.72232| 0| nan| 0|

Sorry, I can't reproduce your problem.

I try to run the ResNet152, sphereface2 with batchsize 64 on 8 x V100. Now, the epoch has reached 19 but there is no nan value in the loss.

Could you give more detail about the training?

**Comment by greatnoble** [comment]
Thank you for your comments on my issue.
Nan values ​​didn't occur every time.
If I tried training about 10 times for the same setting, 9 times learning ended normally, and once a nan value occurred as above.
Below is the training config I used.

I try to run the ResNet152, sphereface2 with batchsize 128 on 8 x A100.

### train configuraton

exp_dir: exp/ResNet152-TSTP-emb256-fbank80-num_frms200-aug0.6-spTrue-saFalse-Sphereface2-SGD-epoch150
gpus: "[0,1,2,3,4,5,6,7]"
num_avg: 10
enable_amp: False # whether enable automatic mixed precision training

seed: 42
num_epochs: 150
save_epoch_interval: 5 # save model every 5 epochs
log_batch_interval: 100 # log every 100 batchs

dataloader_args:
  batch_size: 128
  num_workers: 16
  pin_memory: False
  prefetch_factor: 8
  drop_last: True

dataset_args:
  shuffle: True
  shuffle_args:
    shuffle_size: 2500
  resample_rate: 16000
  speed_perturb: True
  num_frms: 200
  aug_prob: 0.6 # prob to add reverb & noise aug per sample
  fbank_args:
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 1.0
  spec_aug: False
  spec_aug_args:
    num_t_mask: 1
    num_f_mask: 1
    max_t: 10
    max_f: 8
    prob: 0.6

model: ResNet152 # ResNet18, ResNet34, ResNet50, ResNet101, ResNet152
model_init: null
model_args:
  feat_dim: 80
  embed_dim: 256
  pooling_func: "TSTP" # TSTP, ASTP, MQMHASTP
  two_emb_layer: False
projection_args:
  project_type: "sphereface2" # add_margin, arc_margin, sphere, sphereface2, softmax, arc_margin_intertopk_subcenter
  scale: 32.0
  easy_margin: False

margin_scheduler: MarginScheduler
margin_update:
  initial_margin: 0.0
