### ISSUE TITLE
When calculating DER, is overlapping taken into account?

### ISSUE THREAD

**Issue by Zhubisong** [wenet-e2e/wespeaker#189]
When I use the process provided by WeSpeaker(example of VoxConverse) on the AMI dataset, I end up with a result of 27.54(DER), so I wonder if overlap is taken into account when calculating DER? If so, what parameters should be changed so that overlap is not taken into account when calculating DER?

**Comment by JiJiJiang** [comment]
The overlapped regions are counted in default when using the ``md-eval.pl`` script. You can add the ``-1`` parameter to ignore the overlap.
<img width="551" alt="image" src="https://github.com/wenet-e2e/wespeaker/assets/23723621/9dad9255-f0e8-4602-8680-1ef0667df1c0">

**Comment by Zhubisong** [comment]
Thanks!
