### ISSUE TITLE
compute_cosine_score 方法调用报错

### ISSUE THREAD

**Issue by suifengqjn** [wenet-e2e/wespeaker#190]
import wespeakerruntime as wespeaker
speaker = wespeaker.Speaker(lang='chs')
wav1_path = "./1.wav"
wav2_path = "./2.wav"
emb1 = speaker.extract_embedding(wav1_path)
emb2 = speaker.extract_embedding(wav2_path)
score = speaker.compute_cosine_score(emb1, emb2)
print(score)

错误提示：

Traceback (most recent call last):
  File "/home/score2.py", line 8, in <module>
    score = speaker.compute_cosine_score(emb1, emb2)
  File "/usr/local/lib/python3.9/site-packages/wespeakerruntime/speaker.py", line 173, in compute_cosine_score
    return np.dot(emb1,
ValueError: shapes (1,256) and (1,256) not aligned: 256 (dim 1) != 1 (dim 0)

**Comment by cdliang11** [comment]
https://github.com/wenet-e2e/wespeaker/pull/141

**Comment by suifengqjn** [comment]
已解决
