### ISSUE TITLE
如果我想识别机器异常的声音，可以直接替换数据集吗？

### ISSUE THREAD

**Issue by 827379852** [wenet-e2e/wespeaker#197]

**Comment by JiJiJiang** [comment]
如果只是正常声音与非正常声音，可以考虑直接分类的形式

**Comment by Hunterhuan** [comment]
可以。

机器声音异常检测和说话人特征提取方法近似：

1. 如果数据集有异常正常标签，可以考虑直接进行分类。
2. 如果只有正常数据，可以考虑用其他标签来作为分类的代理任务，训练完成提取得到的embedding，可以通过后端检测LOF/KNN/Cosine等方式找到离群异常点。

**Comment by 827379852** [comment]
好的好的 感谢

**Comment by 827379852** [comment]
还有个问题想请教一下，假如我的类别只有两类，正常和异常，但是由于环境因素，机器的正常声音有着明显区别，这种时多分类好呢还是二分类好呢？

**Comment by Hunterhuan** [comment]
需要自己进行尝试吧。

**Comment by 827379852** [comment]
好的 感谢啦

**Comment by 827379852** [comment]
![image](https://github.com/wenet-e2e/wespeaker/assets/79695576/498346c6-65d5-4c8c-bcc1-9c7369359bd6)
这个是我的训练日志，再加入margin后准确率直接变成了0，这个是考虑直接不适用margin吗？

**Comment by JiJiJiang** [comment]
简单的分类任务，softmax ce loss就够用了哈，margin意义不大了

**Comment by 827379852** [comment]
![image](https://github.com/wenet-e2e/wespeaker/assets/79695576/9f47fc1e-825e-4016-acad-224c3e685fd9)

我把输出层改成了softmax一直报错这个，是什么原因呢？

**Comment by cdliang11** [comment]
@827379852 是拉取的最新代码吗

**Comment by outman-goutian** [comment]
机器异音检测，只有正常音频的情况下，可以通过构建一些辅助任务(例如对机器状态等元信息分类，AE等）来提取embedding，在利用knn等离群值算法。

**Comment by wsstriving** [comment]
There are no new updates at this time, so I'll be closing this. Feel free to reopen if needed.
