### ISSUE TITLE
wespeaker的预训练模型测试声纹对比报错

### ISSUE THREAD

**Issue by myhaha** [wenet-e2e/wespeaker#198]
使用wespeaker的预训练模型测试声纹对比报错，显示没有extract_embedding_wav该方法，你们遇到过吗
<img width="1672" alt="image" src="https://github.com/wenet-e2e/wespeaker/assets/38137923/76ec9390-c758-4c33-b8d7-b2c07597bac8">
<img width="1066" alt="image" src="https://github.com/wenet-e2e/wespeaker/assets/38137923/79fb563f-e75a-41f3-bf34-68dae6dd7a1d">

**Comment by cdliang11** [comment]
readme写错了，欢迎提个pr改一下 😊

**Comment by wsstriving** [comment]
Have we fixed this already?

**Comment by cdliang11** [comment]
> Have we fixed this already?

https://github.com/wenet-e2e/wespeaker/pull/201
