### ISSUE TITLE
about the dino logger

### ISSUE THREAD

**Issue by JINzezhong7** [wenet-e2e/wespeaker#199]
非常感谢您可以开源这个项目，我最近再根据您的项目复现dino，您可以提供一下eacpa-tdnn在dino的训练日志吗，我前几轮的eer我发现都有14.多。 非常感谢

**Comment by wntg** [comment]
后面就下降了

**Comment by JINzezhong7** [comment]
我是用一张3090 train的，目前40轮的结果是7.6 。请问目前是正常的吗，还有我在训的时候我发现train loss并不是单调下降的

**Comment by Hunterhuan** [comment]
抱歉，之前训练的log并没有保存。

这个issue先暂时关闭了，如果还有任何疑问，欢迎随时讨论。
