### ISSUE TITLE
外部训练集上，同一模型，不同训练轮次的模型推理速度差异很大

### ISSUE THREAD

**Issue by mingleliuxx** [wenet-e2e/wespeaker#202]
你好，我在使用外部数据集进行训练的时候，使用的默认的ecapa的config。训练完成后，所保存的不同轮次的模型，会出现推理速度上的差异，最大的差异会到10倍左右。请问这里该如何解决？
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/95e3636f-5c10-4fc0-a3f6-7480b9fed5fe)
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/a0f3ef8e-710d-4d25-a531-f022dad6ce0c)
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/ba2eea25-47b4-4518-8ffa-e7b7a4e1c9ca)
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/1be66553-8d2d-4aac-8ae8-00aa387a7148)

**Comment by JiJiJiang** [comment]
![企业微信截图_aecb3c59-d10c-4ff5-bd1e-0d95decb8c6b](https://github.com/wenet-e2e/wespeaker/assets/23723621/cc9378fc-a650-4b16-8e75-17b452d8dc68)

**Comment by JiJiJiang** [comment]
感觉是机器不稳定，有多任务同时在跑导致rtf不稳定，建议同个模型多跑几次看看

**Comment by mingleliuxx** [comment]
> 感觉是机器不稳定，有多任务同时在跑导致rtf不稳定，建议同个模型多跑几次看看

我在运行推理代码时，后台是空载的。此外，单个推理过程我会for循环20次再统计。按理说是排除了机器的影响了

**Comment by JiJiJiang** [comment]
> > 感觉是机器不稳定，有多任务同时在跑导致rtf不稳定，建议同个模型多跑几次看看
> 
> 我在运行推理代码时，后台是空载的。此外，单个推理过程我会for循环20次再统计。按理说是排除了机器的影响了

很诡异，可以换台机器跑跑看哈

**Comment by mingleliuxx** [comment]
> > > 感觉是机器不稳定，有多任务同时在跑导致rtf不稳定，建议同个模型多跑几次看看
> > 
> > 
> > 我在运行推理代码时，后台是空载的。此外，单个推理过程我会for循环20次再统计。按理说是排除了机器的影响了
> 
> 很诡异，可以换台机器跑跑看哈

换过机器了，跟机器没关系的，提的RTF的问题是稳定复现的。另外用torchsummary和torchprofile都测试过了，两个模型的参数和macs都是一样的。

**Comment by mingleliuxx** [comment]
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/d351d079-10e8-43ef-bf31-c2ef5d20e1e1)
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/31dead00-7e5c-4389-8832-f16781428218)
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/02935acf-11e7-43b7-acd0-3db9b4fdfcae)
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/2421c8c4-46ed-4922-bb3c-a4c382cf71ff)
![image](https://github.com/wenet-e2e/wespeaker/assets/125060093/5fe56b9a-f23c-4955-9b9a-f358d476c511)

**Comment by mingleliuxx** [comment]
导出onnx是一样的结论的。
解决办法是减小正则化的值，从而增大权重，防止权重的绝对值太小导致推理缓慢。

**Comment by cdliang11** [comment]
> 导出onnx是一样的结论的。 解决办法是减小正则化的值，从而增大权重，防止权重的绝对值太小导致推理缓慢。

纯好奇：你对比的是 model-1 和 model-60，看结果相差都有一个数量级了 🤕 ,  训练后期模型（model-60, model-65)相差的大吗
