### ISSUE TITLE
windows 编译 onnxruntime 后，执行提取部分音频embedding会出现异常

### ISSUE THREAD

**Issue by wxbool** [wenet-e2e/wespeaker#205]
执行命令以及输出日志：
```
extract_emb_main.exe --wav_list wav_scp.txt                        --result result.txt                        --speaker_model_path models/cnceleb_resnet34_LM.onnx                        --embedding_size 256                        --SamplesPerChunk  80000
I1008 10:29:00.920819  6684 extract_emb_main.cc:39] Init model ...
I1008 10:29:00.922801  6684 speaker_engine.cc:37] Reading model models/cnceleb_resnet34_LM.onnx
I1008 10:29:00.922801  6684 speaker_engine.cc:39] Embedding size: 256
I1008 10:29:00.922801  6684 speaker_engine.cc:41] per_chunk_samples: 80000
I1008 10:29:00.922801  6684 speaker_engine.cc:43] Sample rate: 16000
I1008 10:29:02.459808  6684 onnx_speaker_model.cc:60] Ouput name: feats
I1008 10:29:02.465803  6684 onnx_speaker_model.cc:68] Output name: embs
I1008 10:29:02.468802  6684 extract_emb_main.cc:44] embedding size: 256
I1008 10:29:03.410821  6684 extract_emb_main.cc:84] process: aa-01 RTF: 0.171875
I1008 10:29:03.469822  6684 extract_emb_main.cc:84] process: aa-02 RTF: 0.0070864
```

运行过程中，出现弹窗错误，错误信息如下：

Microsoft Visual C++ Runtime Library
Debug Assertion Failed!
Program:
...aker runtime onnxruntime build bin\Debug extract emb main.exeFile: G: Program Files Microsoft VisualStudio 2022 Community VC Tool MSVC 14.34.31933 include vectorLine: 112
Expression: cannot seek vector iterator after end
For information on how your program can cause an assertionfailure, see the Visual C++ documentation on asserts.
(Press Retry to debug the application)

![image](https://github.com/wenet-e2e/wespeaker/assets/29696787/fd899aca-05ca-4f38-a617-136811bd49c2)

音频文件：
[wav.zip](https://github.com/wenet-e2e/wespeaker/files/12839621/wav.zip)

**Comment by JiJiJiang** [comment]
@cdliang11

**Comment by cdliang11** [comment]
是否是c++版本的问题

**Comment by wxbool** [comment]
> 是否是c++版本的问题

gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 

cmake version 3.26.0-rc2

请教一下，我该如何排查？

**Comment by cdliang11** [comment]
> > 是否是c++版本的问题
> 
> gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
> 
> cmake version 3.26.0-rc2
> 
> 请教一下，我该如何排查？

看起来不像是版本问题。你这边可以试着定位下程序执行到哪一步报的错误

**Comment by wsstriving** [comment]
No updates for a long time, reopen if needed.
