### ISSUE TITLE
QMF and fusion in VoxCeleb Speaker Recognition Challenge 2023 papers

### ISSUE THREAD

**Issue by wendongj** [wenet-e2e/wespeaker#206]
greatly thanks to the project of speaker verification. in VoxSRC 2023, many team use QMF and ASnorm to improve the score, seems QMF is as good as ASnorm, if it is possible to add the QMF in this project? and they also use Fusion to fuse different model result, seems this can improve performance too. sorry to ask these requirement.

**Comment by JiJiJiang** [comment]
1. QMF will be supported soon.
2. There are several ways of fusions: score fusion, embedding average and score, etc. It is easy to implement I think.

**Comment by wendongj** [comment]
> 1. QMF will be supported soon.
> 2. There are several ways of fusions: score fusion, embedding average and score, etc. It is easy to implement I think.

really thanks for your reply, I will fuse them as you recommend.

**Comment by wsstriving** [comment]
> 1. QMF will be supported soon.
> 2. There are several ways of fusions: score fusion, embedding average and score, etc. It is easy to implement I think.
@Hunterhuan Can you follow this?

**Comment by wsstriving** [comment]
@Hunterhuan Can you give a brief schedule on this topic?

**Comment by Hunterhuan** [comment]
> @Hunterhuan Can you give a brief schedule on this topic?

sure, I am current working on it. I will immediately contribute the QMF, once the code is completed. 
This will take approximately two weeks.

**Comment by wsstriving** [comment]
@Hunterhuan Any update?

**Comment by WhXmURandom** [comment]
> > @Hunterhuan Can you give a brief schedule on this topic?
> 
> sure, I am current working on it. I will immediately contribute the QMF, once the code is completed. This will take approximately two weeks.

Hello, when will the code for QMF be updated?

**Comment by wsstriving** [comment]
@Hunterhuan I will pin this issue for high priority

**Comment by Hunterhuan** [comment]
> greatly thanks to the project of speaker verification. in VoxSRC 2023, many team use QMF and ASnorm to improve the score, seems QMF is as good as ASnorm, if it is possible to add the QMF in this project? and they also use Fusion to fuse different model result, seems this can improve performance too. sorry to ask these requirement.

Score calibration is implemented for both voxceleb and cnceleb. Ref: https://github.com/wenet-e2e/wespeaker/pull/320

**Comment by wsstriving** [comment]
The PR https://github.com/wenet-e2e/wespeaker/pull/320 has been merged
