### ISSUE TITLE
cannot import ‘silero_vad’

### ISSUE THREAD

**Issue by WhXmURandom** [wenet-e2e/wespeaker#220]
<img width="577" alt="import" src="https://github.com/wenet-e2e/wespeaker/assets/109778621/9ed25797-2f7a-4204-b8f7-61e54b7fd1af">

**Comment by robin1001** [comment]
pip install git+https://github.com/pengzhendong/silero-vad.git

**Comment by WhXmURandom** [comment]
感谢！
