### ISSUE TITLE
model.recognize 方法问题

### ISSUE THREAD

**Issue by RadyGyd** [wenet-e2e/wespeaker#236]
bug_fix
model.recognize 方法中 best_score 需要小于score
需要将 best_name 最终赋值为result['name']

**Comment by cdliang11** [comment]
欢迎提个pr～

**Comment by RadyGyd** [comment]
已提交~




Rady&nbsp;Gu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenet-e2e/wespeaker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月22日(星期三) 下午3:24
***@***.***&gt;;
抄送:&nbsp;"Rady ***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenet-e2e/wespeaker] model.recognize 方法问题 (Issue #236)





 
欢迎提个pr～
