### ISSUE TITLE
What sampling rate was the model trained on?

### ISSUE THREAD

**Issue by youssefabdelm** [wenet-e2e/wespeaker#244]
Trying to run it on many files that are 44.1kHz and not sure if I should downsample to 16kHz before running it through the model or not?

**Comment by wsstriving** [comment]
Yes, you need to downsample it to 16kHz, all the pretrained models currently are trained on 16k data

**Comment by youssefabdelm** [comment]
Thanks so much! And mono as well?

**Comment by JiJiJiang** [comment]
Yes, we support mono only.
BTW, you can set resample_rate as 16k in the config yaml file and resampling would be done during the training process, instead of downsampling all wavs into 16kHZ before training.

**Comment by wsstriving** [comment]
Has been solved
