### ISSUE TITLE
Do we have quantizer of speaker embedding?

### ISSUE THREAD

**Issue by Liu-Feng-deeplearning** [wenet-e2e/wespeaker#247]
Hello,  do we have plan to support quantizer extractor of speaker embedding, such as RVQ/LFQ?

If quantizers of speaker embedding is possible, it is easy to add integer quantizers as prompt to put before audio token(e.g. valle/soundstream).

Thank you for the excellent project.

**Comment by wsstriving** [comment]
Currently, no, thanks for the suggestion. Can you detail why we need such kind of embeddings? I believe it's quite easy for LLM-based TTS systems to take continuous speaker embeddings as input, considering its modeling capacity.

**Comment by wsstriving** [comment]
Closed since no futher discussion is launched. Feel free to re-open it.
