### ISSUE TITLE
fine tuning the pretrained model

### ISSUE THREAD

**Issue by Emo3032** [wenet-e2e/wespeaker#250]
How can i fine tune the pretrained model with my own audio files for speaker verification?
There is no particular tutorial for it and i'm lost

**Comment by wsstriving** [comment]
Documents will be prepared by next week

**Comment by BlowtheWind22** [comment]
> Documents will be prepared by next week

I have problems in training and finetuning. Hope the ducuments be released ASAP.

**Comment by aemonyfchiu** [comment]
> Documents will be prepared by next week

Thank you very much for your work and hopefully the documents can be released soon! I found that I can't load the pretrained models in python codes.

**Comment by JiJiJiang** [comment]
> I have problems in training and finetuning. Hope the ducuments be released ASAP.

Here it comes. Please refer to https://wenet.org.cn/wespeaker
