### ISSUE TITLE
training issue

### ISSUE THREAD

**Issue by BlowtheWind22** [wenet-e2e/wespeaker#260]
![{48A32403-F561-4F7A-822D-FFC3FB54FCA5}](https://github.com/wenet-e2e/wespeaker/assets/84451737/1e272ba2-2f68-4c85-b73b-343ece28e036)
When doing SV training, why am I stuck in this place for hours  ( same problem for VoxCeleb and CnCeleb, data processing is okay ) ?

**Comment by JiJiJiang** [comment]
This is not normal. Have you pull the latest codes?
Try to add some print logs and see where is stuck.
