### ISSUE TITLE
What does LM mean in the model names?

### ISSUE THREAD

**Issue by fjiang9** [wenet-e2e/wespeaker#264]
What's the difference between [ResNet34](https://wespeaker-1256283475.cos.ap-shanghai.myqcloud.com/models/voxceleb/voxceleb_resnet34.zip) and [ResNet34_LM](https://wespeaker-1256283475.cos.ap-shanghai.myqcloud.com/models/voxceleb/voxceleb_resnet34_LM.zip) ?

**Comment by fjiang9** [comment]
Does it mean large margin finetune? https://github.com/wenet-e2e/wespeaker/blob/dcf4b67e6b050dad793be75b570e4e35ecdeb24a/wespeaker/models/projections.py#L261

**Comment by JiJiJiang** [comment]
> Does it mean large margin finetune?
> 
> https://github.com/wenet-e2e/wespeaker/blob/dcf4b67e6b050dad793be75b570e4e35ecdeb24a/wespeaker/models/projections.py#L261

Yes
