### ISSUE TITLE
Train on new Language

### ISSUE THREAD

**Issue by emanueleielo** [wenet-e2e/wespeaker#265]
Hi, there is a recipe to follow on how to train on a new Language?

Thanks a lot

**Comment by JiJiJiang** [comment]
Every stage is the same, except that you should use your own training data of the new language and prepare the wav.scp and utt2spk files.

**Comment by omarabb315** [comment]
@JiJiJiang could you provide some details on preparing the dataset, the current shape of the data is that I am having a couple of thousands of audio clips each paired with the speaker id?

Also will there be anything wrong if the pretrained model is trained on another language?

**Comment by JiJiJiang** [comment]
1. Download the Voxceleb dataset and run prepare_data.sh to see what wav.scp and utt2spk should be. Prepare the same format as they are.
2. It should be OK fine-tuning the pre-trained model with data of another language.

**Comment by omarabb315** [comment]
Thank you for the response @JiJiJiang 
Now I have these fields in the dataset, (audio, text, speaker_id) 
1) Are they enough?
2) And what is the utterance_id?

**Comment by JiJiJiang** [comment]
1. Yes. audio and speaker_id are needed.
2. utterance_id is the utterance name.

**Comment by omarabb315** [comment]
Thank you @JiJiJiang , Now after preparing the data can you provide me with some details about the required steps to fine-tune the pretrained model, like the one [in this link](https://huggingface.co/pyannote/wespeaker-voxceleb-resnet34-LM)

I tried a lot to understand what do you mean by stages from the github but couldn’t get to the right path.

**Comment by emanueleielo** [comment]
> Thank you @JiJiJiang , Now after preparing the data can you provide me with some details about the required steps to fine-tune or pretrain a model, like the one [in this link](https://huggingface.co/pyannote/wespeaker-voxceleb-resnet34-LM)
> 
> I tried a lot to understand what do you mean by stages from the github but couldn’t get to the right path.

https://github.com/wenet-e2e/wespeaker/issues/250
On this issue they say that will prepare the docs but I didn't find it.
Did you found something to fine-tune the pretrain model?

**Comment by omarabb315** [comment]
@emanueleielo unfortunately didn't find any thoughts on how to fine-tune the model

**Comment by emanueleielo** [comment]
> @emanueleielo unfortunately didn't find any thoughts on how to fine-tune the model

@JiJiJiang it would be great to have some information about it, even how much time the trained model has required for the training
