### ISSUE TITLE
想请教训练中的问题

### ISSUE THREAD

**Issue by wcqy-ye** [wenet-e2e/wespeaker#275]
想请问一下为什么会出现这个问题 
这就是一个很简单的res2conv1d
![image](https://github.com/wenet-e2e/wespeaker/assets/46421217/4281d6f2-2353-40fa-bf56-092845e2c941)
报错如下：
![image](https://github.com/wenet-e2e/wespeaker/assets/46421217/5c7b395e-5774-4f16-bec4-fbb07490c7a0)
我在单机单卡训练的时候没有出现这个问题，因此不知道是不是多卡环境下导致对于变量的初始化等有要求，所以想请教一下

**Comment by JiJiJiang** [comment]
为了保证训练完的模型可以支持torch.jit.script导出，在训练一开始会直接检查一遍模型
![image](https://github.com/wenet-e2e/wespeaker/assets/23723621/a4962b0d-1745-4f68-9dd0-e433f1961444)

只需修改一下这个forward函数即可，参考ecapa_tdnn中的改法更改一下即可 https://github.com/wenet-e2e/wespeaker/blob/2968d940df84dfe70c2476b439bbe3113b7d3234/wespeaker/models/ecapa_tdnn.py#L66

**Comment by wcqy-ye** [comment]
那请问这个问题是为什么呢
![image](https://github.com/wenet-e2e/wespeaker/assets/46421217/c01e6b17-d83e-4d73-bc8e-f96665bd2240)
现在判断是在script_model.save(os.path.join(model_dir, 'init.zip'))语句出现问题，但是感觉script_model = torch.jit.script(model)已经检查过了模型为什么还会出错呢 不太理解
![image](https://github.com/wenet-e2e/wespeaker/assets/46421217/bb33ba07-a617-4463-b29b-8752a29c2d36)

**Comment by wcqy-ye** [comment]
问题已经解决了 是因为forward函数中有默认为None的参数
