### ISSUE TITLE
训练问题请教

### ISSUE THREAD

**Issue by wcqy-ye** [wenet-e2e/wespeaker#278]
在我尝试使用自己修改的模型进行训练，出现了以下错误：
<img width="704" alt="企业微信截图_17083345347344" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/c010e0f3-7236-42fe-b66f-edf2333c95cd">
<img width="751" alt="企业微信截图_17083346253262" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/18b27201-854f-44c1-89a5-09679ce98adc">
发现是在dataloader过程中出现问题，但是我尝试这样结果也没有对应输出111
<img width="261" alt="企业微信截图_17083346716900" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/371c46d0-0295-4fbc-88c1-e6e0f6135957">
以及我发现在这个过程中会不断的占用内存直到占用完之后就报上面提到的错误
<img width="778" alt="企业微信截图_17083351855345" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/b6eaf748-08c2-4123-9856-02e5ad7e742e">
以及我在使用您提供的原本示例却没有这个问题出现，所以我猜测可能是我的模型本身和您实例不太匹配？比如池化方法什么的，希望能得到您的回复

**Comment by JiJiJiang** [comment]
看报错的log像是number-worker设置数量太多，dataloader的进程被系统杀死了，并不是什么代码的bug
原因是机器的cpu核数太少，只需减少number-worker数目即可

**Comment by wcqy-ye** [comment]
> 看报错的log像是number-worker设置数量太多，dataloader的进程被系统杀死了，并不是什么代码的bug 原因是机器的cpu核数太少，只需减少number-worker数目即可，在config/xxx.yaml里面修改

非常感谢您的回复，之前的问题解决了，现在又出现一个新的尺寸不匹配的错误：
<img width="708" alt="企业微信截图_17085034481421" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/bb2aa0ce-4b17-45fe-9856-ed5a6920a7ad">
这个res2的模块我是复制您ecapatdnn中的代码，应该是由于这个conv改变了最后一个维度导致的
<img width="440" alt="企业微信截图_17085035995839" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/18f777f2-9dad-47e4-94c9-7458833fb591">
<img width="721" alt="企业微信截图_1708503516314" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/088dfcad-5715-4bf5-a79b-45b963502c26">
但是我运行您原本的示例没有出现这个问题 尺寸没有被改变
<img width="547" alt="企业微信截图_17085041365969" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/7e190020-564a-4f6e-90ac-d126124b0a67">
<img width="741" alt="企业微信截图_17085042255067" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/df23457e-92f1-44f9-af92-c9bddf7d55b3">
想请教一下您认为可以怎么修改呢

**Comment by wcqy-ye** [comment]
<img width="499" alt="企业微信截图_17085065823708" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/05b06231-a3c4-4b66-b6d4-89607898edfc">
发现是padding没有设置 设置padding之后解决了 谢谢您

**Comment by wcqy-ye** [comment]
但是好像目前又出现了另外一个问题
![image](https://github.com/wenet-e2e/wespeaker/assets/46421217/61df4374-233d-4817-b821-f46e44d42a95)

**Comment by wcqy-ye** [comment]
> 但是好像目前又出现了另外一个问题 ![image](https://private-user-images.githubusercontent.com/46421217/306711846-61df4374-233d-4817-b821-f46e44d42a95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODgxNzEsIm5iZiI6MTcwODU4Nzg3MSwicGF0aCI6Ii80NjQyMTIxNy8zMDY3MTE4NDYtNjFkZjQzNzQtMjMzZC00ODE3LWI4MjEtZjQ2ZTQ0ZDQyYTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA3NDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOTU0NDg3ZDY2NDZkNDhkYzIxNDQ1MWU1MmZhMmFhN2MxYjNlZjEyNzY2YWNlMzE5MzVmZjI3ODEyNDYwMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wzs6691AdbXXTCDzFPCPedmCk7ZVpPQxG_m3UUM8UcE)

问题已经解决了 设置find_unused_parameters=False解决
<img width="582" alt="企业微信截图_17085884463726" src="https://github.com/wenet-e2e/wespeaker/assets/46421217/d6072e15-e0f6-473a-abf4-b002b630c638">
