### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by wcqy-ye** [wenet-e2e/wespeaker#280]
请问这个问题怎么解决或者代码该怎么修改呢：
RuntimeError: 
Expected integer literal for index. ModuleList/Sequential indexing is only supported with integer literals. Enumeration is supported, e.g. 'for index, v in enumerate(self): ...':
  File "/memory/wespeaker/wespeaker/models/ds_tdnn.py", line 265
                y_i = x_i
            elif i == 1:
                y_i = self.blocks[i - 1](x_i)
                      ~~~~~~~~~~~~~~~~~~ <--- HERE
            else:
                y_i = self.blocks[i - 1](x_i + y_i)
![image](https://github.com/wenet-e2e/wespeaker/assets/46421217/90af51cf-ca1f-406c-8050-bc99819b67ab)
这里本来用的就是enumerate呀。。

**Comment by JiJiJiang** [comment]
如果你不需要训练后导出script model，可以直接注释掉train.py里面的这两行格式检查的代码
![image](https://github.com/wenet-e2e/wespeaker/assets/23723621/1a304205-a54d-45d9-a737-e4f1cee35c8d)

**Comment by wcqy-ye** [comment]
> 如果你不需要训练后导出script model，可以直接注释掉train.py里面的这两行格式检查的代码 ![image](https://private-user-images.githubusercontent.com/23723621/307656303-1a304205-a54d-45d9-a737-e4f1cee35c8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTgyMTksIm5iZiI6MTcwODk5NzkxOSwicGF0aCI6Ii8yMzcyMzYyMS8zMDc2NTYzMDMtMWEzMDQyMDUtYTU0ZC00NWQ5LWE3MzctZTRmMWNlZTM1YzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAxMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYjQ3NzYyYTllZjE2Y2EyMzQwYmU5MTdkY2I4YzljZjhjZjFmNDM4N2VmY2VlMTFkMzRkM2Q1ZWMwYjMwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N1n5V6pRs-S8bzv9JAR5JuH-N4Ro_zv2fvTow0n6f28)

好的 谢谢！
