### ISSUE TITLE
Could you please provide the pt file and oonx file of the pre-trained ECAPA-TDNN model?

### ISSUE THREAD

**Issue by Zhubisong** [wenet-e2e/wespeaker#284]
I can't find the corresponding file in this repository, I want to use your model as the baseline model in the paper, can you provide the corresponding file?

**Comment by JiJiJiang** [comment]
Thank you for your comment.
We will upload the ECAPA-TDNN models trained on voxceleb dataset.

**Comment by Zhubisong** [comment]
Thank you for uploading. However, I have some questions/advice. 
1. I do not know what happen, but when I use voxceleb_ECAPA_512LM extract embeddings for VoxConverse, the dimension of embedding is 192, no 512.
2. I did some experiments on Dihard1 and AMI SDM, and I found that ResNet34 without LM performed better than ResNet34LM (ADAPTIVE LARGE MARGIN FINE-TUNING FOR ROBUST SPEAKER VERIFICATION may account for this, LM is useful for long audio, while the segments used in Speaker Diarization are short), while on VoxConverse LM is better. I want to know would you please upload ECAPA without LM?

**Comment by JiJiJiang** [comment]
done

**Comment by wsstriving** [comment]
Finished, check https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md
