### ISSUE TITLE
pre-trained models trained on only voxceleb1

### ISSUE THREAD

**Issue by sidhantls** [wenet-e2e/wespeaker#289]
I'm benchmarking speaker embedding models, for speaker verifications, that are trained and tested on the [voxceleb1 dataset](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1.html). I am referring to the pre-trained models list [here](https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md) but it looks like these models are trained on voxceleb2? if this is the case, are there any pre-trained models that have been trained on voxceleb1?

**Comment by JiJiJiang** [comment]
1. Sorry that we do not train any models on the voxceleb1 dev set, for it only has 1211 speakers, which is not enough for training a well-performed speaker verification system. You can try to train on voxceleb1 dataset using our codes and have a comparison.
2. We follow the protocol used in the VoxSRC challenge series. Training on the voxceleb2 dev dataset while testing on the whole voxceleb1 dataset, including vox1-O, vox1-E, and vox1-H, is widely-used for benchmarking. You can consider this setup.
