### ISSUE TITLE
Convert Speaker Recognition Pre trained Pytorch Model to CoreML model to support in iOS

### ISSUE THREAD

**Issue by akshaydevelops** [wenet-e2e/wespeaker#302]
I am trying to convert the Speaker recognition Pytorch model(_.pt_) to CoreML (_.mlmodel_) to integrate in an iOS app.

I followed the steps mentioned in the official tutorial video:
[Convert PyTorch models to Core ML : Apple Developer Tech Talk](https://developer.apple.com/videos/play/tech-talks/10154)

But the scripts are getting failed with multiple reasons.

Question 1: Is it really possible to convert this model to CoreML Model?
Question 2: If so, can someone help me in converting so?

**Comment by wsstriving** [comment]
@robin1001 @cdliang11 Do you have related experiences?

**Comment by cdliang11** [comment]
Sorry, I don't have related experience.

**Comment by akshaydevelops** [comment]
@cdliang11 
I tried using [CoreML Tools](https://apple.github.io/coremltools/docs-guides/source/convert-pytorch.html#), as the [onnx-coreml](https://github.com/onnx/onnx-coreml) is deprecated.

I have used `export_jit.py` as reference and tried both Tracing and scripting approaches using `coremltools`.

_**I am not sure how to correctly pass the `input` parameters for `trace` and `convert` functions.**_


```
from __future__ import print_function

import argparse
import os

import torch
import yaml
import coremltools as ct

from wespeaker.models.speaker_model import get_speaker_model
from wespeaker.utils.checkpoint import load_checkpoint


def get_args():
    parser = argparse.ArgumentParser(description='export your script model')
    parser.add_argument('--config', required=True, help='config file')
    parser.add_argument('--checkpoint', required=True, help='checkpoint model')
    parser.add_argument('--output_file', required=True, help='output file')
    parser.add_argument('--tracing', default=True, action=argparse.BooleanOptionalAction)
    args = parser.parse_args()
    return args


def main():
    args = get_args()
    # No need gpu for model export
    os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

    with open(args.config, 'r') as fin:
        configs = yaml.load(fin, Loader=yaml.FullLoader)
    model = get_speaker_model(configs['model'])(**configs['model_args'])
    print("model Loaded successfully")

    load_checkpoint(model, args.checkpoint)
    model.eval()
    
    # Tracing approach
    if args.tracing:
    
        print('Using Tracing approach')
        
        example_input = torch.rand(1, 3, 64, 64)
        traced_model = torch.jit.trace(model, example_input)
        
        mlmodel = ct.convert(traced_model, inputs=[ct.TensorType(name="input", shape=example_input.shape)], minimum_deployment_target=ct.target.iOS13)
        mlmodel.save(args.output_file)
        
        print('Export model successfully, see {}'.format(args.output_file))
        
    else:
        print('Using scripting aproach')
        
        scripted_model = torch.jit.script(model)
        
        mlmodel = ct.converters.convert(scripted_model, inputs=[ct.TensorType(shape=(1, 3, 64, 64))], minimum_deployment_target=ct.target.iOS13)
        mlmodel.save(args.output_file)
        
        print('Export model successfully, see {}'.format(args.output_file))

if __name__ == '__main__':
    main()

```
## Tracing approach error
<img width="1501" alt="Tracing approach Error" src="https://github.com/wenet-e2e/wespeaker/assets/80538371/c3c26bb3-2766-488d-939e-70a891f8418f">

## Scripting approach error
<img width="1356" alt="Scripting approach Error" src="https://github.com/wenet-e2e/wespeaker/assets/80538371/5904af6f-9e47-4f40-ba39-e9a6ac8b2b0d">

**Comment by cdliang11** [comment]
The dimension of `example_input` is 3, egs: `example_input= [1,200,80]`

**Comment by cdliang11** [comment]
@akshaydevelops 
Assuming you are using the resnet model and the pooling function is TSTP (pooling_func: "TSTP"). Then modify the `class TSTP(nn.Module)` in `wespeaker/models/pooling_layers.py` to the following code:

```python
class TSTP(nn.Module):
    """
    Temporal statistics pooling, concatenate mean and std, which is used in
    x-vector
    Comment: simple concatenation can not make full use of both statistics
    """

    def __init__(self, in_dim=0, **kwargs):
        super(TSTP, self).__init__()
        self.in_dim = in_dim

    def var(self, x, dim, keepdim=False):
        input_means = torch.mean(x, dim=dim, keepdim=True)
        differences = x - input_means
        squared_deviations = torch.square(differences)
        variance = torch.mean(squared_deviations, dim=dim, keepdim=keepdim)
        return variance

    def forward(self, x):
        # The last dimension is the temporal axis
        pooling_mean = x.mean(dim=-1)
        # pooling_std = torch.sqrt(torch.var(x, dim=-1) + 1e-7)
        pooling_std = torch.sqrt(self.var(x, dim=-1) + 1e-7)


        pooling_mean = pooling_mean.flatten(start_dim=1)
        pooling_std = pooling_std.flatten(start_dim=1)
        stats = torch.cat((pooling_mean, pooling_std), 1)
        return stats

    def get_out_dim(self):
        self.out_dim = self.in_dim * 2
        return self.out_dim
```
Similar modifications can be made to other code that uses `torch.var() or tensor.var()`.

**Comment by akshaydevelops** [comment]
@cdliang11 I'm assuming the above changes requires the model to be rebuild and train the model again.

as per https://github.com/apple/coremltools/issues/1203#issuecomment-2048023128, There's a way where we can use the custom `var` function during the export, using `@register_torch_op()` from https://apple.github.io/coremltools/docs-guides/source/composite-operators.html#using-composite-ops-with-pytorch-conversion

**_Can we do something like below for the `var` function implementation, which will not require the entire model recreation.?_**

```python
@register_torch_op()
def var(context, node):
    inputs = _get_inputs(context, node, expected=4)
    x = inputs[0]
    axes = inputs[1].val

    # Ensure axes is a list of integers, e.g., [2, 3] for the last two dimensions (Change #3)
    assert isinstance(axes, list) and all(isinstance(axis, int) for axis in axes)

    # Assert we can have biased divisor (N). (Change #1)
    assert(inputs[2].val == False)

    keepdim = True  # Set keepdim to True for broadcasting (Change #2)

    x_mean = mb.reduce_mean(x=x, axes=axes, keep_dims=keepdim)
    x_sub_mean = mb.sub(x=x, y=x_mean)  # Broadcasting should work here (Change #4)
    x_sub_mean_square = mb.square(x=x_sub_mean)
    x_var = mb.reduce_mean(x=x_sub_mean_square, axes=axes, keep_dims=keepdim)

    context.add(x_var, torch_name=node.name)
```

**Comment by akshaydevelops** [comment]
Hey @cdliang11 , @wsstriving 

I'm able to export the Pytorch model to CoreML Model using the below torch operation.

```python
@register_torch_op()
def var(context, node):
    inputs = _get_inputs(context, node, expected=4)

    x = inputs[0]
    axes = inputs[1].val
    keepdim = True

    x_mean = mb.reduce_mean(x=x, axes=axes, keep_dims=keepdim)
    x_sub_mean = mb.sub(x=x, y=x_mean)
    x_sub_mean_square = mb.square(x=x_sub_mean)
    x_var = mb.reduce_mean(x=x_sub_mean_square, axes=axes, keep_dims=keepdim)

    context.add(x_var, torch_name=node.name)
```   
 Can someone help me on passing the `task`, `audio_file` & `audio_file2` inputs to CoreML Model using the MultiArray(Float32 1 × 200 × 80)?

   
<img width="1122" alt="Wespeaker_ML_Preview" src="https://github.com/wenet-e2e/wespeaker/assets/80538371/022711f8-4b9c-48af-9d0c-2e5bf4fd7cf5">

**Comment by wsstriving** [comment]
> Hey @cdliang11 , @wsstriving
> 
> I'm able to export the Pytorch model to CoreML Model using the below torch operation.
> 
> ```python
> @register_torch_op()
> def var(context, node):
>     inputs = _get_inputs(context, node, expected=4)
> 
>     x = inputs[0]
>     axes = inputs[1].val
>     keepdim = True
> 
>     x_mean = mb.reduce_mean(x=x, axes=axes, keep_dims=keepdim)
>     x_sub_mean = mb.sub(x=x, y=x_mean)
>     x_sub_mean_square = mb.square(x=x_sub_mean)
>     x_var = mb.reduce_mean(x=x_sub_mean_square, axes=axes, keep_dims=keepdim)
> 
>     context.add(x_var, torch_name=node.name)
> ```

Good to know you've finally found a workaround! Currently, the `ncnn` branch supports the replacement of the `var` operation. You can take a look at it.

By the way, it would be great if you could help make a pull request for Apple platform support. Thank you very much!
