### ISSUE TITLE
How to solve: cannot import name 'vad' from 'silero_vad' 

### ISSUE THREAD

**Issue by shinshoji01** [wenet-e2e/wespeaker#304]
In the latest version of "silero_vad", they have updated the structure of the repo and `vad.py` is no longer available in the folder "silero_vad". Therefore, the following part causes an error when you `import wespeaker`.

https://github.com/wenet-e2e/wespeaker/blob/5b8330bb5cbef4cdb9bd435eef0b8b78bff4c8e5/wespeaker/cli/speaker.py#L20

Therefore, we need to specify the commit id of the repository "silero_vad". I suggest the following update.
- Before

https://github.com/wenet-e2e/wespeaker/blob/5b8330bb5cbef4cdb9bd435eef0b8b78bff4c8e5/requirements.txt#L24

- After
```
silero-vad @ git+https://github.com/pengzhendong/silero-vad.git@cfcc62358aec92084a003521a3673874082529c3

**Comment by JiJiJiang** [comment]
@pengzhendong Please follow this issue. There are recent updates in your repo https://github.com/pengzhendong/silero-vad.git. It seems that the vad.py file was deleted.
What is the difference between silero_vad.py and the original vad.py?  And how to fix this error here?

**Comment by pengzhendong** [comment]
> @pengzhendong Please follow this issue. There are recent updates in your repo https://github.com/pengzhendong/silero-vad.git. It seems that the vad.py file was deleted. What is the difference between silero_vad.py and the original vad.py? And how to fix this error here?

I changed it. I will upload it to pypi and make a pr. No difference.

**Comment by JiJiJiang** [comment]
fixed！

**Comment by wsstriving** [comment]
Close as it has been fixed
