### ISSUE TITLE
silero vad's API has changed, requiring code modifications.

### ISSUE THREAD

**Issue by BongkiLee** [wenet-e2e/wespeaker#305]
silero vad's API has changed, requiring code modifications.
Line 20 of wespeaker/cli/speaker.py 
**from silero_vad import vad**
It must be modified to **from silero_vad import SileroVAD as vad** to perform without error.

**Comment by JiJiJiang** [comment]
Thanks for your issue. We will fix this error soon.

**Comment by JiJiJiang** [comment]
Please also check https://github.com/wenet-e2e/wespeaker/issues/304

**Comment by JiJiJiang** [comment]
fixed!

**Comment by BongkiLee** [comment]
Thanks for the quick fix.

**Comment by wsstriving** [comment]
Close as it has been fixed
