### ISSUE TITLE
Could not find a version that satisfies the requirement silero-vad error while installing wespeaker

### ISSUE THREAD

**Issue by Racketycomic** [wenet-e2e/wespeaker#332]
I tried installing wespeaker in 2 methods 
Method 1: Clone the wespeaker repo and do pip install -e .
Method 2 : do direct pip install pip install git+https://github.com/wenet-e2e/wespeaker.git

both of them are giving the following error : 

ERROR: Could not find a version that satisfies the requirement silero-vad (unavailable) (from wespeaker) (from versions: 5.0.1b2)
ERROR: No matching distribution found for silero-vad (unavailable)

**Comment by Racketycomic** [comment]
I tried doing pip install silero-vad@git+https://github.com/pengzhendong/silero-vad.git to check if that installation works properly but i got the following error :

![image](https://github.com/wenet-e2e/wespeaker/assets/33209062/d1843e8c-423c-4dbd-850f-77e29ec20380)

Then i tried replacing the silero-vad@git+https://github.com/pengzhendong/silero-vad.git this with pysilero-vad in setup.py file and this successfully allowed me to install the wespeaker

**Comment by pengzhendong** [comment]
Sorry, I renamed my project in order to transfer the pypi name to the official silero-vad organization. I will fix it tomorrow.

**Comment by pengzhendong** [comment]
fixed. https://github.com/wenet-e2e/wespeaker/pull/333
