### ISSUE TITLE
add_reverb_noise支持多通道rir和musan吗

### ISSUE THREAD

**Issue by woodyzhuo** [wenet-e2e/wespeaker#348]
你好，使用过程中报错以下
wespeaker/dataset/processor.py", line 435, in add_reverb_noise     out_audio = signal.convolve(audio, rir_audio,
ValueError: volume and kernel should have the same dimensionality
查看了一下代码，发现dataset/processor.py中函数add_reverb_noise不支持rir和noise中为多通道？
是嘛

**Comment by JiJiJiang** [comment]
是的 目前只支持单通道的
