### ISSUE TITLE
windows上安装报错

### ISSUE THREAD

**Issue by yumianhuli1** [wenet-e2e/wespeaker#362]
Collecting texterrors (from nemo_toolkit[asr]!=1.22.0,!=1.23.0->-r requirements.txt (line 2))
  Downloading http://mirrors.aliyun.com/pypi/packages/9b/47/9a391643961698df3c804172f005e8b56c9693c14c4170abd9d3c961e971/texterrors-0.5.1.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

File "D:\whisper-diarization\venv\lib\site-packages\setuptools\installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['D:\\whisper-diarization\\venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\win11\\AppData\\Local\\Temp\\tmpaawrz79k', '--quiet', 'pybind11']' returned non-zero exit status 1.
      [end of output]

**Comment by cdliang11** [comment]
发错issue了吗？错误信息看起来不是和wespeaker相关的

**Comment by wsstriving** [comment]
Close first, please reopen if needed
