### ISSUE TITLE
Download voxceleb script requests a password 

### ISSUE THREAD

**Issue by tcourat** [wenet-e2e/wespeaker#368]
Hi,

I am trying to use the voxceleb recipe. However I am not able to download the voxceleb dataset using the provided wget command as it seems to request a password or authentification. Is the link outdated ?

Thanks.

**Comment by MSokar-NU** [comment]
Same Issue

**Comment by tcourat** [comment]
> It's not an issue with the downloading link itself; rather, the growing concern over privacy and the implications of collecting data that contains Personally Identifiable Information (PII) has become increasingly prominent. As a result, the link may have been disabled by the official team.

I understand this point. I found a different way to get the dataset on HuggingFace, so I will just skip the download_data.sh script.
