### ISSUE TITLE
 the SimAMResNet pretrain models downloads

### ISSUE THREAD

**Issue by smehrabikia** [wenet-e2e/wespeaker#369]
Hi,

It seems that the download link for the SimAMResNet models is not working, and the model cannot be downloaded. Could you please check and fix the issue?

Thank you!

**Comment by JiJiJiang** [comment]
That is strange, I can download [SimAMResNet34](https://wenet.org.cn/downloads?models=wespeaker&version=voxblink2_samresnet34.zip). Which model did you download ?

**Comment by smehrabikia** [comment]
Yes, I was able to download it now, but it wasn't available for download two weeks ago.
Thank you.
