### ISSUE TITLE
pip install {git url} doesn't install the requirements

### ISSUE THREAD

**Issue by domklement** [wenet-e2e/wespeaker#371]
Hi,

I've just run `pip install git+https://github.com/wenet-e2e/wespeaker.git` in a new conda enviroment and got bunch of missing modules errors, such as `umap, hdbscan, ...`. It seems like the setup doesn't install requirements.

I'm using Python 3.11.

Dominik

**Comment by JiJiJiang** [comment]
Yes, Thank you for your question. umap+hdbscan is our newly-supported clustering method in diarization recipe. We added these requirements in the outside requirements.txt, bug forgot to add them in the cli installing setup.

We have fixed this problem (https://github.com/wenet-e2e/wespeaker/pull/372). Just have a try! Feel free to ask any questions if there are still problems, thanks!

**Comment by domklement** [comment]
That was fast. I will try for sure. Thank you a lot!
