### ISSUE TITLE
单机多卡训练，仅GPU=0有利用率，其他卡GPU利用率=0%

### ISSUE THREAD

**Issue by YMLLG** [wenet-e2e/wespeaker#373]
单机多卡训练，只有GPU=0这张卡的利用率=100%，其他卡GPU利用率=0%，如何修复这个问题

![image](https://github.com/user-attachments/assets/d321d261-91af-4d24-b47e-3fece3a6d7d6)

**Comment by JiJiJiang** [comment]
请问第一张卡的训练是正常的吗？

**Comment by YMLLG** [comment]
问题解决了， 减少batch_size
