### ISSUE TITLE
DINO pretrained model

### ISSUE THREAD

**Issue by hsiaohan0827** [wenet-e2e/wespeaker#378]
Hi, thanks for sharing the code!
Could you share the pretrained model of DINO (https://github.com/wenet-e2e/wespeaker/tree/c047286bfafb09ee263600f8f52aac02c089b041/examples/voxceleb/v3/dino) if there's one?
It would be really helpful for me, thanks a lot!

**Comment by cdliang11** [comment]
@Hunterhuan Please follow this

**Comment by cdliang11** [comment]
> Hi, thanks for sharing the code! Could you share the pretrained model of DINO (https://github.com/wenet-e2e/wespeaker/tree/c047286bfafb09ee263600f8f52aac02c089b041/examples/voxceleb/v3/dino) if there's one? It would be really helpful for me, thanks a lot!

https://github.com/wenet-e2e/wespeaker/pull/394

**Comment by wsstriving** [comment]
Done as Finished
