### ISSUE TITLE
onnx 形式的预训练模型固定了帧长是有什么特别的考虑吗？

### ISSUE THREAD

**Issue by songfuture** [wenet-e2e/wespeaker#380]
首先非常感谢如此优秀的项目！
请教一下，
1. 导出的onnx形式的预训练模型的帧数维为什么是固定的200而不是动态的任意帧数？是结合了训练模型的chunk包含的帧数考虑的吗？还是考虑了CMN阶段的帧数要求？
2. 如果固定帧数为200，当一条语音包含的帧数不是200的整数倍时，应该如何处理剩余的帧？如语音包含278帧，[0:200]帧可以用onnx模型进行推理，剩余的78帧应该如何使用模型进行推理呢？用[78:278]把剩余的78帧也利用起来，还是[200:278]重复至200帧送入onnx进行推理呢？

**Comment by cdliang11** [comment]
非常感谢对这个项目的关注！

导出onnx支持动态维度，如下：
https://github.com/wenet-e2e/wespeaker/blob/e9bbf73d0fd13db6cf42a6cb2eafb0d7dd0f8e0e/wespeaker/bin/export_onnx.py#L84-L88

**Comment by songfuture** [comment]
> 非常感谢对这个项目的关注！
> 
> 导出onnx支持动态维度，如下：
> 
> https://github.com/wenet-e2e/wespeaker/blob/e9bbf73d0fd13db6cf42a6cb2eafb0d7dd0f8e0e/wespeaker/bin/export_onnx.py#L84-L88

**Comment by songfuture** [comment]
> > 非常感谢对这个项目的关注！
> > 导出onnx支持动态维度，如下：
> > https://github.com/wenet-e2e/wespeaker/blob/e9bbf73d0fd13db6cf42a6cb2eafb0d7dd0f8e0e/wespeaker/bin/export_onnx.py#L84-L88

请问一下如何获得发布的预训练模型的config呢，这样才能重新导出动态帧数维的预训练onnx模型？
<img width="622" alt="image" src="https://github.com/user-attachments/assets/01d70176-b149-44b4-9bd2-ef04dd411564">

**Comment by cdliang11** [comment]
> 请问一下如何获得发布的预训练模型的config呢，这样才能重新导出动态帧数维的预训练onnx模型？ <img alt="image" width="622" src="https://private-user-images.githubusercontent.com/37433088/379638269-01d70176-b149-44b4-9bd2-ef04dd411564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTIwNTUsIm5iZiI6MTcyOTc1MTc1NSwicGF0aCI6Ii8zNzQzMzA4OC8zNzk2MzgyNjktMDFkNzAxNzYtYjE0OS00NGI0LTliZDItZWYwNGRkNDExNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA2MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOTJlODc0ZDdiZjgwMmI3ZWJhMzcxODM2MjBiNDY4ZjU4YmY3NWUzOTRlNDA4MWJlMWMyYTA1ZjAyODlmOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vva_NqVVdZ1rwg_B2MgY5v-AngJxhIfLXUHcJX-ZpU8">

你好，预训练模型下载页面：https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md，里边提供了pytorch模型（包含config文件）和onnx模型，其中onnx模型是动态维度。

**Comment by songfuture** [comment]
<img width="956" alt="image" src="https://github.com/user-attachments/assets/6a13edef-e440-4e74-931e-83797bb45e81">
使用预训练模型时https://wenet.org.cn/downloads?models=wespeaker&version=voxblink2_samresnet34.onnx，会提示帧数不匹配，请问是还需要改什么参数吗？

**Comment by cdliang11** [comment]
抱歉，这个onnx导出的有问题，变成了固定长度。 我们会重新导出并上传。

**Comment by songfuture** [comment]
> 抱歉，这个onnx导出的有问题，变成了固定长度。 我们会重新导出并上传。
> 
> 另外，你也可以利用pt模型，重新导出onnx。 https://wenet.org.cn/downloads?models=wespeaker&version=voxblink2_samresnet34.zip
> 
> 导出命令如下：
> 
> ```shell
> python wespeaker/bin/export_onnx.py --config voxblink2_samresnet34/config.yaml --checkpoint voxblink2_samresnet34/avg_model.pt --output_model voxblink2_samresnet34/final.onnx
> ```

谢谢您的建议，按要求重新导出动态帧数维的模型后，想对这个模型做一些finetune，但是没有在预训练模型的配置文件中https://wenet.org.cn/downloads?models=wespeaker&version=voxblink2_samresnet34.zip 发现optimizer和学习率变化策略的配置，请问有更详细的配置文件有说明这两点吗？

**Comment by cdliang11** [comment]
> > 抱歉，这个onnx导出的有问题，变成了固定长度。 我们会重新导出并上传。
> > 另外，你也可以利用pt模型，重新导出onnx。 https://wenet.org.cn/downloads?models=wespeaker&version=voxblink2_samresnet34.zip
> > 导出命令如下：
> > ```shell
> > python wespeaker/bin/export_onnx.py --config voxblink2_samresnet34/config.yaml --checkpoint voxblink2_samresnet34/avg_model.pt --output_model voxblink2_samresnet34/final.onnx
> > ```
> 
> 谢谢您的建议，按要求重新导出动态帧数维的模型后，想对这个模型做一些finetune，但是没有在预训练模型的配置文件中https://wenet.org.cn/downloads?models=wespeaker&version=voxblink2_samresnet34.zip 发现optimizer和学习率变化策略的配置，请问有更详细的配置文件有说明这两点吗？

see https://github.com/wenet-e2e/wespeaker/issues/365
