### ISSUE TITLE
Inquiry regarding "WARNING:root:unexpected tensor: projection.weight"

### ISSUE THREAD

**Issue by greatnoble** [wenet-e2e/wespeaker#381]
@JiJiJiang 

Thank you so much for providing such a fantastic speaker recognition tool.

I tested "Command Line Usage", and the following warning message occurred.

"WARNING:root:unexpected tensor: projection.weight"

I installed all packages according to the installation guide.

Will there be any performance impact if the warning message occurs?

If there is a solution to the warning message, please guide me.

Thank you

**Comment by JiJiJiang** [comment]
Thank you for your question, 

There isn't any performance impact caused by the warning.
We saved the whole model in the checkpoint. However, when inferring the model to obtain the speaker embeddings, we don't need the  projection module (mapping embeddings to training speakers).

**Comment by greatnoble** [comment]
@JiJiJiang 

Thank you for your quick and detailed reply.

**Comment by greatnoble** [comment]
Thank you

**Comment by greatnoble** [comment]
Thank you
