### ISSUE TITLE
请问这个问题怎么解决ImportError: cannot import name 'load_silero_vad' from 'silero_vad'

### ISSUE THREAD

**Issue by wcqy-ye** [wenet-e2e/wespeaker#382]
![image](https://github.com/user-attachments/assets/19f38df7-65b4-4a47-b8fa-6ff2bac1806d)
我之前用过wespeaker也安装了之前版本的silero_vad，现在出现了这个问题，我看了之前issue提到过这个问题，但好像不管是直接使用
 silero-vad @ git+https://github.com/pengzhendong/silero-vad.git
还是旧版本
silero-vad @ git+https://github.com/pengzhendong/silero-vad.git@cfcc62358aec92084a003521a3673874082529c3
都不能解决这个问题
想请问下是怎么解决的

**Comment by cdliang11** [comment]
重新安装silero-vad试试
```
pip uninstall silero-vad
pip install silero-vad==5.1.2
```

**Comment by wcqy-ye** [comment]
好的 解决了 谢谢
