### ISSUE TITLE
wespeaker多机多卡训练

### ISSUE THREAD

**Issue by wcqy-ye** [wenet-e2e/wespeaker#383]
您好 我看到之前有说过wespeaker支持多机多卡训练，我现在有172.16.0.101和172.16.0.102两台机器 请问怎么配置可以实现多机多卡训练

**Comment by cdliang11** [comment]
已加多机多卡支持。请参考：https://github.com/wenet-e2e/wespeaker/pull/389

以voxceleb/v2为例：
```bash
bash run.sh --stage 3 --stop-stage 3 --HOST_NODE_ADDR "xxx.xxx.xxx.xxx:port" --num_nodes num_node
```

**Comment by wcqy-ye** [comment]
> @wcqy-ye 已加多机多卡支持。请参考：#389
> 
> 以voxceleb/v2为例，假设有两台机器，ip地址使用你提供的，选172.16.0.101为master节点:
> 
> ```shell
> # 在172.16.0.101执行
> bash run.sh --stage 3 --stop-stage 3 --HOST_NODE_ADDR "172.16.0.101:23333" --num_nodes 2
> # 在172.16.0.102执行
> bash run.sh --stage 3 --stop-stage 3 --HOST_NODE_ADDR "172.16.0.101:23333" --num_nodes 2
> ```

好的 非常感谢！
