### ISSUE TITLE
想请问在说话人日志的结果怎么看对应参数

### ISSUE THREAD

**Issue by wcqy-ye** [wenet-e2e/wespeaker#387]
![image](https://github.com/user-attachments/assets/32ac6695-7ea1-424d-ac58-6c64203d5a19)
不好意思 想请问下在这个结果中怎么看对应的参数
DER = MISS + FALSE ALARM + SPEAKER CONFUSION (%)
DER看到是4.94 MISS是2.93那个吗 FA是0吗 那请问SPEAKER CONFUSION是哪个呢 还是说根据这个公式通过其他三个参数算出SPEAKER CONFUSION?

**Comment by JiJiJiang** [comment]
MiSSED SPEAKER TIME
FALARM SPEAKER TIME
SPEAKER ERROR TIME

**Comment by wcqy-ye** [comment]
> MiSSED SPEAKER TIME 2.3 FALARM SPEAKER TIME 0.0 SPEAKER ERROR TIME 2.6

好的 谢谢！
