### ISSUE TITLE
Any number about the performance (i.e. EER) that WeSpeaker can achieve?

### ISSUE THREAD

**Issue by mycrazycracy** [wenet-e2e/wespeaker#74]
Hi,

WeSpeaker implements many useful training and test tools in speaker verfication. It's awesome! However, in the repo, it seems that there is no information about how is the performance (EER, minDCF, etc.) on VoxCeleb and VoxConverse. 

It would be very helpful if this information can be provided. The developers can use this information to check whether they use WeSpeaker in the correct way. The researchers can use this number to compare with the SOTA system. 

Please inform me if I miss something. 😄

**Comment by cdliang11** [comment]
Hi, this information can be found in the example/xxx/README.md. :blush:

**Comment by mycrazycracy** [comment]
Oh, just miss that... Sorry for the convenience...

One more question: is the result reported here stable if you train the model multiple times?

**Comment by JiJiJiang** [comment]
> Oh, just miss that... Sorry for the convenience...
> 
> One more question: is the result reported here stable if you train the model multiple times?

Yes, I think it is stable. We don't deliberately tune the hyper-params many times for better results.
Besides, the training configs of Voxceleb and Cnceleb recipes are almost the same (see conf/xxx.yaml for details), which also proves the generalization ability of our systems in different datasets using different models.

**Comment by JiJiJiang** [comment]
> Oh, just miss that... Sorry for the convenience...
> 
> One more question: is the result reported here stable if you train the model multiple times?

Thank you for your recommendation. We will add Voxceleb results in the main README.md.

**Comment by mycrazycracy** [comment]
Thank you for the reply!
