### ISSUE TITLE
Training instruction

### ISSUE THREAD

**Issue by Spectra456** [wenet-e2e/wespeaker#79]
Is there any guide to launch training? I tried to run run.sh, but nothing is printed(

**Comment by JiJiJiang** [comment]
Hi, the parameters in run.sh, "stage" and "stop_stage" are both -1 in default, which means running nothing.
As shown below, you can modify them to run some specific stages.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/23723621/187080833-cd25e966-af51-4ebc-b180-30b23b3db5b8.png">

For example, if you want to run stage 1~7, you can run "bash run.sh --stage 1 --stop_stage 7"

**Comment by Spectra456** [comment]
Hi, thank you for your answer and this repository!

**Comment by JiJiJiang** [comment]
It's a pleasure. BTW, all you need is to follow the run.sh and run it stage by stage. If everything goes well, you can get a similar result as ours.
