### ISSUE TITLE
How to evaluate

### ISSUE THREAD

**Issue by angelabr** [wenet-e2e/wespeaker#80]
Hi,

Could you tell me which script I need to run in order to evaluate the pretrained model for voxceleb? I would like to test it with a different dataset.

Thank you

**Comment by wsstriving** [comment]
Hi, based on the [voxceleb recipe](https://github.com/wenet-e2e/wespeaker/blob/master/examples/voxceleb/v2/run.sh) (This is also the recipe you should follow), we provided the pretrained models as described [here](https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md) for embedding extraction, which gives you two options,
1. Refer to stage `4`, `local/extract_vox.sh` for embedding extraction instructions, you need to download the [pt version](https://wespeaker-1256283475.cos.ap-shanghai.myqcloud.com/models/voxceleb/voxceleb_resnet34_LM.pt)  and use the default config file in the recipe.
2. You can use the [onnx version](https://wespeaker-1256283475.cos.ap-shanghai.myqcloud.com/models/voxceleb/voxceleb_resnet34_LM.onnx) and refer to the  [onnx inference demo](https://github.com/wenet-e2e/wespeaker/blob/master/wespeaker/bin/infer_onnx.py) to extract embeddings, and use `kaldiio` to save it to the required format, check [this line](https://github.com/wenet-e2e/wespeaker/blob/036393c4a8ec18eb379ca627452de916a5a03fbb/wespeaker/bin/extract.py#L76) as a reference

After you get the embeddings, you can refer to stage `5` and stage `6` for the scoring process
