### ISSUE TITLE
For pretrain model

### ISSUE THREAD

**Issue by TaoRuijie** [wenet-e2e/wespeaker#82]
Thanks for your amazing open source code, very great work and I learnt a lot from that, really appreciate!

So if you have trained it, could you please share the pretrained model (.pt file) on the VoxCeleb2 for the large-scale ResNet? Such as ResNet152 or ResNet101 model? Thanks a lot!

**Comment by czy97** [comment]
We don't have these pre-trained model yet, you can just change the model type in config.yaml to train it. Maybe later we will upload this model if we have time to train it.

**Comment by TaoRuijie** [comment]
Sure thanks! Got it

**Comment by EmreOzkose** [comment]
Hi @czy97. Is there any progress for this issue?

**Comment by wsstriving** [comment]
> Hi @czy97. Is there any progress for this issue?

Will upload resnet152, resnet221, and resnet293 models trained on the voxceleb dataset in two days, I will update the [pretrained page](https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md) when this is done.

**Comment by EmreOzkose** [comment]
Thank you @wsstriving.

**Comment by wsstriving** [comment]
@EmreOzkose @TaoRuijie New models have been added, please check the [pretrained page](https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md)
