### ISSUE TITLE
For training speed

### ISSUE THREAD

**Issue by mmmmayi** [wenet-e2e/wespeaker#93]
I try to train the ResNet model on voxceleb2 with 3 2080Ti and find that the training is slow (about 6 hours for one epoch). Is it normal and is there any function to reduce the training time?

**Comment by JiJiJiang** [comment]
May I know which data type you use? shard or raw?

**Comment by cdliang11** [comment]
This may not be normal. I use 2 2080Ti to train ResNet34 model on voxceleb2-dev with shard or raw, and one epoch takes 30 to 40 minutes.  The cpu is Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz.

**Comment by JiJiJiang** [comment]
> 

Em... Cpu performance could be an important reason. Maybe you can try a smaller batch size or use more "num_workers".

**Comment by wsstriving** [comment]
Could reopen if requested, not a common problem to fix
