### ISSUE TITLE
Question about num_class used in pretrained model

### ISSUE THREAD

**Issue by mmmmayi** [wenet-e2e/wespeaker#96]
Hi, I download the checkpoint of pre-trained ResNet-34 for voxceleb and find the num_class of projections is 17982. I think you use this num_class during training as well because the shape of projection.weight is [256,17982]. I am just curious why 17982 instead of 5994?

**Comment by cdliang11** [comment]
Hi,  during training, we randomly change the speed of an utterance with a ratio of 0.9 or 1.1, and the augmented audios will be treated as from new speakers due to the pitch shift after the augmentation. So 17982 = 5994 x 3.

**Comment by mmmmayi** [comment]
I see, thank you
