### ISSUE TITLE
DDP error

### ISSUE THREAD

**Issue by zds-potato** [wenet-e2e/wespeaker#98]
When I trained the VoxCeleb dataset, the following problem occurred that prevented the training. Is there a way to fix it? I am sure the environment was installed as prompted.

![image](https://user-images.githubusercontent.com/83072078/201178847-d5d3677c-337b-4e91-b030-033089014268.png)

**Comment by cdliang11** [comment]
Hi, could you provide more detailed error information ?

**Comment by zds-potato** [comment]
There should be a problem with using multiple gpus.
```
Start training ...
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
  File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
    fire.Fire(train)
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    fire.Fire(train)
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component, remaining_args = _CallAndUpdateTrace(
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 61, in train
    dist.barrier()  # let the rank 0 mkdir first
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    component = fn(*varargs, **kwargs)
  File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 61, in train
    dist.barrier()  # let the rank 0 mkdir first
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180487213/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180487213/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1416724) of binary: anaconda3/envs/wespeaker/bin/python
Traceback (most recent call last):
  File "anaconda3/envs/wespeaker/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
wespeaker/bin/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-11-11_11:03:57
  host      : x1
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1416725)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-11_11:03:57
  host      : x1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1416724)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by cdliang11** [comment]
> There should be a problem with using multiple gpus.
> 
> ```
> Start training ...
> WARNING:torch.distributed.run:
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
>     fire.Fire(train)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
>     fire.Fire(train)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component, remaining_args = _CallAndUpdateTrace(
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 61, in train
>     dist.barrier()  # let the rank 0 mkdir first
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
>     component = fn(*varargs, **kwargs)
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 61, in train
>     dist.barrier()  # let the rank 0 mkdir first
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180487213/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
> ncclUnhandledCudaError: Call to CUDA function failed.
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180487213/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
> ncclUnhandledCudaError: Call to CUDA function failed.
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1416724) of binary: anaconda3/envs/wespeaker/bin/python
> Traceback (most recent call last):
>   File "anaconda3/envs/wespeaker/bin/torchrun", line 33, in <module>
>     sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
>     return f(*args, **kwargs)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
>     run(args)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
>     elastic_launch(
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> wespeaker/bin/train.py FAILED
> ------------------------------------------------------------
> Failures:
> [1]:
>   time      : 2022-11-11_11:03:57
>   host      : x1
>   rank      : 1 (local_rank: 1)
>   exitcode  : 1 (pid: 1416725)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2022-11-11_11:03:57
>   host      : x1
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 1416724)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```

Sorry, I don't have this problem. It may be an environmental problem.

**Comment by cdliang11** [comment]
Sorry, I don't have this problem. It may be an environmental problem.

**Comment by JiJiJiang** [comment]
> There should be a problem with using multiple gpus.
> 
> ```
> Start training ...
> WARNING:torch.distributed.run:
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
>     fire.Fire(train)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
>     fire.Fire(train)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component, remaining_args = _CallAndUpdateTrace(
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 61, in train
>     dist.barrier()  # let the rank 0 mkdir first
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
>     component = fn(*varargs, **kwargs)
>   File "wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 61, in train
>     dist.barrier()  # let the rank 0 mkdir first
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2709, in barrier
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180487213/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
> ncclUnhandledCudaError: Call to CUDA function failed.
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1639180487213/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled cuda error, NCCL version 21.0.3
> ncclUnhandledCudaError: Call to CUDA function failed.
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1416724) of binary: anaconda3/envs/wespeaker/bin/python
> Traceback (most recent call last):
>   File "anaconda3/envs/wespeaker/bin/torchrun", line 33, in <module>
>     sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
>     return f(*args, **kwargs)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
>     run(args)
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
>     elastic_launch(
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> wespeaker/bin/train.py FAILED
> ------------------------------------------------------------
> Failures:
> [1]:
>   time      : 2022-11-11_11:03:57
>   host      : x1
>   rank      : 1 (local_rank: 1)
>   exitcode  : 1 (pid: 1416725)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2022-11-11_11:03:57
>   host      : x1
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 1416724)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```

It seems like an NCCL error. Please check your NCCL version and cuda driver version (whether compatible with cuda 11.0).

**Comment by zds-potato** [comment]
Thanks very much. I will check it.

**Comment by WhiteFu** [comment]
> Thanks very much. I will check it.

I also met a similar problem. Have you solved it。
